crates/apollo-parser/src/parser/grammar/operation.rs
crates/apollo-parser/test_data/parser/ok/0033_directive_on_argument_definition.txt
crates/apollo-parser/test_data/parser/ok/0034_query_shorthand_followed_by_fragment_definition.graphql
crates/apollo-parser/test_data/parser/ok/0034_query_shorthand_followed_by_fragment_definition.txt

fixes #101
We were not accommodating parsing any other types following a query shorthand:
```graphql
{
id
name
...friendsFields
}
fragment friendsFields on User {
id
name
}
```
This PR allows for the AST to be built for these sorts of queries as well.

allow types to follow query shorthand definitions

---

crates/apollo-parser/src/lexer/mod.rs
crates/apollo-parser/src/parser/grammar/document.rs
crates/apollo-parser/src/parser/mod.rs

We were not removing the current token from the token vector when creating errors, which caused some continuous looping. That is, the parser kept parsing the same syntactically incorrect token, without breaking when it should have been.
fixes #104

fix: pop current token off when creating a syntax error

---

crates/apollo-parser/benches/peek_n.rs
crates/apollo-parser/src/parser/mod.rs

Fix #108
related to https://github.com/apollographql/router/issues/100
this avoids collecting the list of tokens in peek_n and peek_data_n. When running the benchmarks locally, I get:
- on e6e79d684b6f26df02e12633b6f10fa589c1d67b 25µs per iteration
- on 625fa4665cd37f280d5828f7a17220cdcee16472 11µs per iteration

Optimize peek n

---

crates/apollo-parser/README.md
crates/apollo-parser/examples/unused_vars.rs
crates/apollo-parser/src/ast/mod.rs
crates/apollo-parser/src/error.rs
crates/apollo-parser/src/lexer/mod.rs
crates/apollo-parser/src/lib.rs
crates/apollo-parser/src/parser/grammar/object.rs
crates/apollo-parser/src/parser/grammar/selection.rs
crates/apollo-parser/src/parser/grammar/union_.rs
crates/apollo-parser/src/parser/grammar/value.rs
crates/apollo-parser/src/parser/mod.rs
crates/apollo-parser/src/parser/syntax_tree.rs
crates/apollo-parser/src/tests.rs

fixes #119 
ast.errors() now return an `Iter<'_, crate::Error>` which allows us to iterate, but also check for the `len()` (through ExactSizeIterator). It should allow us to use `is_empty()` as well eventually, if / when https://github.com/rust-lang/rust/issues/35428 lands.
I wish we could use `is_empty()`, the ergonomics feel a bit clunky without it. I would totally understand if we decided not to return an impl Iterator, or something else for this reason.

feat: impl Iterator for errors

---

crates/apollo-parser/src/parser/grammar/ty.rs
crates/apollo-parser/src/parser/grammar/variable.rs
crates/apollo-parser/test_data/lexer/err/0006_unterminated_string_value_followed_by_valid_tokens.graphql
crates/apollo-parser/test_data/parser/err/0010_input_definition_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0012_input_extension_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0014_interface_extension_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0016_object_type_extension_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0028_invalid_type_system_extension_followed_by_valid.txt
crates/apollo-parser/test_data/parser/ok/0008_directive_definition_with_arguments.txt
crates/apollo-parser/test_data/parser/ok/0009_directive_definition_repeatable.txt
crates/apollo-parser/test_data/parser/ok/0014_input_definition.txt
crates/apollo-parser/test_data/parser/ok/0015_input_extension.txt
crates/apollo-parser/test_data/parser/ok/0016_interface_definition.txt
crates/apollo-parser/test_data/parser/ok/0017_interface_extension.txt
crates/apollo-parser/test_data/parser/ok/0018_object_type_definition.txt
crates/apollo-parser/test_data/parser/ok/0019_object_type_extension.txt
crates/apollo-parser/test_data/parser/ok/0021_operation_type_definition_with_arguments.txt
crates/apollo-parser/test_data/parser/ok/0022_operation_type_definition_with_arguments_and_directives.txt
crates/apollo-parser/test_data/parser/ok/0028_union_type_definition_followed_by_object_definition.txt
crates/apollo-parser/test_data/parser/ok/0031_variables_with_default.txt
crates/apollo-parser/test_data/parser/ok/0032_supergraph.txt
crates/apollo-parser/test_data/parser/ok/0033_directive_on_argument_definition.txt
crates/apollo-parser/test_data/parser/ok/0035_query_with_variables.graphql
crates/apollo-parser/test_data/parser/ok/0035_query_with_variables.txt

fixes #125
whenever a NAMED_TYPED, LIST_TYPE, NON_NULL_TYPE are created, they are automatically get created as part of the TYPE node, so we do not need to start it manually. This fix makes it possible to once again do:
```rust
if let ast::Type::NamedType(name) = var.ty().unwrap() {
assert_eq!(name.name().unwrap().text().as_ref(), "Int")
}
```

fix(apollo-parser): properly create TYPE's NAMED_TYPE, LIST_TYPE, NON_NULL_TYPE

---

crates/apollo-parser/src/parser/grammar/variable.rs
crates/apollo-parser/test_data/parser/ok/0036_parses_variable_definition_with_list_type.graphql
crates/apollo-parser/test_data/parser/ok/0036_parses_variable_definition_with_list_type.txt

fixes #131
Variable definition was previously not accepting a LIST_TYPE, which is incorrect. This commit fixes this issue.

fix(apollo-parser): variable definition can have a LIST_TYPE

---

crates/apollo-parser/src/parser/grammar/selection.rs
crates/apollo-parser/test_data/parser/ok/0037_operation_type_definition_with_inline_fragment.graphql
crates/apollo-parser/test_data/parser/ok/0037_operation_type_definition_with_inline_fragment.txt

This will mostly act as an example in case users are looking for how to work with nested selections and get their FIELD/INLINE_FRAGMENT/FRAGMENT_SPREAD.
closes #136

chore(apollo-parser): add a test for nested SELECTION_SETs

---

crates/apollo-parser/examples/annotate_snippet.rs
crates/apollo-parser/src/parser/grammar/ty.rs
crates/apollo-parser/test_data/parser/err/0010_input_definition_with_missing_name.txt
crates/apollo-parser/test_data/parser/ok/0014_input_definition.txt
crates/apollo-parser/test_data/parser/ok/0032_supergraph.txt
crates/apollo-parser/test_data/parser/ok/0037_operation_type_definition_with_inline_fragment.txt
crates/apollo-parser/test_data/parser/ok/0038_wrapped_named_types.graphql
crates/apollo-parser/test_data/parser/ok/0038_wrapped_named_types.txt

We are missing BANG token in the AST when a NON_NULL_TYPE gets created. Although the node created is indeed NON_NULL_TYPE, it's also important to keep the original set of tokens. The NON_NULL_TYPE after this commit looks like this:
```txt
- NON_NULL_TYPE@38..47
- WHITESPACE@38..43 "\n    "
- NAMED_TYPE@43..46
- NAME@43..46
- IDENT@43..46 "Int"
- BANG@46..47 "!"
```
fixes #142

fix(apollo-parser): bump BANG token when creating NON_NULL_TYPE

---

crates/apollo-parser/src/parser/grammar/selection.rs
crates/apollo-parser/src/parser/grammar/ty.rs
crates/apollo-parser/src/parser/mod.rs
crates/apollo-parser/test_data/parser/err/0010_input_definition_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0012_input_extension_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0014_interface_extension_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0016_object_type_extension_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0028_invalid_type_system_extension_followed_by_valid.txt
crates/apollo-parser/test_data/parser/ok/0008_directive_definition_with_arguments.txt
crates/apollo-parser/test_data/parser/ok/0009_directive_definition_repeatable.txt
crates/apollo-parser/test_data/parser/ok/0014_input_definition.txt
crates/apollo-parser/test_data/parser/ok/0015_input_extension.txt
crates/apollo-parser/test_data/parser/ok/0016_interface_definition.txt
crates/apollo-parser/test_data/parser/ok/0017_interface_extension.txt
crates/apollo-parser/test_data/parser/ok/0018_object_type_definition.txt
crates/apollo-parser/test_data/parser/ok/0019_object_type_extension.txt
crates/apollo-parser/test_data/parser/ok/0021_operation_type_definition_with_arguments.txt
crates/apollo-parser/test_data/parser/ok/0022_operation_type_definition_with_arguments_and_directives.txt
crates/apollo-parser/test_data/parser/ok/0028_union_type_definition_followed_by_object_definition.txt
crates/apollo-parser/test_data/parser/ok/0031_variables_with_default.txt
crates/apollo-parser/test_data/parser/ok/0032_supergraph.txt
crates/apollo-parser/test_data/parser/ok/0033_directive_on_argument_definition.txt
crates/apollo-parser/test_data/parser/ok/0037_operation_type_definition_with_inline_fragment.txt
crates/apollo-parser/test_data/parser/ok/0038_wrapped_named_types.graphql
crates/apollo-parser/test_data/parser/ok/0038_wrapped_named_types.txt

This re-writes the parsing logic for TYPE nodes to have an easier time accounting for ignored tokens and their correct place in the AST. An intermediate representation of the TYPE and it's nullability and list status is created and then processed to put the correct tokens in their spots.
Before this commit this sort of query
```graphql
mutation MyMutation($custId: Int!, $b: String) {
myMutation(custId: $custId)
}
```
would result the `ast.document.to_string()` to have this output:
```graphql
mutation MyMutation($custId: , Int!$b:  String) {
myMutation(custId: $custId)
}
```
which is incorrect. The `to_string()` now results in the exact same output, as the AST created is correct.
fixes #143

fix(apollo-parser): add ignored tokens to TYPE nodes in correct place

---

crates/apollo-parser/src/parser/grammar/operation.rs

`operation_definition` is called in a loop where the we never progress
in which tokens we're looking at.
Pop while reporting the error such that progress can be made.

Replace `p.err` with `p.err_and_pop` to prevent infinite loop.

---

crates/apollo-parser/src/parser/grammar/operation.rs
crates/apollo-parser/test_data/parser/err/0030_operation_definition_with_description.graphql
crates/apollo-parser/test_data/parser/err/0030_operation_definition_with_description.txt

Avoids creating an operation definition node when an unrelated token is popped off in the parsing of operation definition nodes.
Instead of having an incorrect AST for input `"description"{}`
```
- DOCUMENT@0..2
- OPERATION_DEFINITION@0..0
- OPERATION_DEFINITION@0..2
- SELECTION_SET@0..2
- L_CURLY@0..1 "{"
- R_CURLY@1..2 "}"
```
We are now correctly creating an AST that looks like this:
```
- DOCUMENT@0..2
- OPERATION_DEFINITION@0..2
- SELECTION_SET@0..2
- L_CURLY@0..1 "{"
- R_CURLY@1..2 "}"
```
Additionally, we are adding an correctly testing for number of errors and definitions in the AST when a description precedes an Operation Definition. We are also adding an error test case to the test suite with a description before an operation definition.

apollo-parser: update operation definition tests for #158

---

crates/apollo-parser/src/ast/generated/nodes.rs
crates/apollo-parser/test_data/parser/ok/0039_variable_with_directives.graphql
crates/apollo-parser/test_data/parser/ok/0039_variable_with_directives.txt
graphql.ungram

While the parser was correctly parsing and accounting for directives in a variable definition, the getter for `Directives` in `VariableDefinition` type in the AST was missing. This commit makes an addition to the graphql ungrammar, and by extension the generated AST nodes API.

fix(apollo-parser): variable definition has optional directives

---

crates/apollo-encoder/CHANGELOG.md
crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/src/argument.rs
crates/apollo-encoder/src/directive_def.rs
crates/apollo-encoder/src/document.rs
crates/apollo-encoder/src/field.rs
crates/apollo-encoder/src/input_value.rs
crates/apollo-encoder/src/lib.rs
crates/apollo-encoder/src/string_value.rs
crates/apollo-parser/examples/unused_vars.rs
crates/apollo-parser/src/parser/grammar/selection.rs
crates/apollo-parser/src/parser/grammar/value.rs
crates/apollo-parser/src/parser/mod.rs
crates/apollo-smith/Cargo.toml
crates/apollo-smith/src/document.rs
crates/apollo-smith/src/input_value.rs

Bugs detected when implementing the new version of apollo encoder into Rover (https://github.com/apollographql/rover/pull/1017)

fix(apollo-encoder): do not trim double quotes when needed, rename method input_object_ and type InputValueDef for consistency

---

.cargo/config

It seems like there is an issue with CircleCI running cargo install over ssh instead of https. This commit attempts to enforce an https:// install in cargo's config.

chore(ci): enforce https:// for cargo fetches

---

crates/apollo-parser/src/parser/syntax_tree.rs

Adds `PartialEq`, `Eq` and `Clone` derives. These are necessary to feed the SyntaxTree to salsa in #202, but I am sure will be quite handy for other reasons.

feat(apollo-parser): impl PartialEq, Eq and Clone on SyntaxTree

---

crates/apollo-encoder/README.md
crates/apollo-encoder/src/argument.rs
crates/apollo-encoder/src/directive_def.rs
crates/apollo-encoder/src/document.rs
crates/apollo-encoder/src/enum_def.rs
crates/apollo-encoder/src/enum_value.rs
crates/apollo-encoder/src/field.rs
crates/apollo-encoder/src/input_field.rs
crates/apollo-encoder/src/input_object_def.rs
crates/apollo-encoder/src/input_value.rs
crates/apollo-encoder/src/interface_def.rs
crates/apollo-encoder/src/object_def.rs
crates/apollo-encoder/src/scalar_def.rs
crates/apollo-encoder/src/schema_def.rs
crates/apollo-encoder/src/string_value.rs
crates/apollo-encoder/src/union_def.rs
crates/apollo-smith/src/argument.rs
crates/apollo-smith/src/directive.rs
crates/apollo-smith/src/enum_.rs
crates/apollo-smith/src/field.rs
crates/apollo-smith/src/input_object.rs
crates/apollo-smith/src/input_value.rs
crates/apollo-smith/src/interface.rs
crates/apollo-smith/src/object.rs
crates/apollo-smith/src/scalar.rs
crates/apollo-smith/src/schema.rs
crates/apollo-smith/src/union.rs

This PR introduces clearer (more readable) serialization for descriptions used in input value definitions. If any of the input value definitions in a given field definition comes with a description, we will multiline all input value definitions. That is to say, instead of serializing arguments definition like this:
```graphql
type Foo {
"This is a description of the \`one\` field."
one("This is a description of the \`argument\` argument." argument: InputType!): Type
}
```
we serialize it as:
```graphql
type Foo {
"This is a description of the \`one\` field."
one(
"This is a description of the \`argument\` argument."
argument: InputType!
): Type
}
```
This makes it a lot more readable, especially for users with a large number of input value definitions with descriptions.
In the process …

Update description serialization for input value definitions

---

crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/src/input_field.rs
crates/apollo-encoder/src/input_object_def.rs
crates/apollo-encoder/src/input_value.rs
crates/apollo-encoder/src/variable.rs
crates/apollo-smith/Cargo.toml
crates/apollo-smith/src/input_value.rs
crates/apollo-smith/src/variable.rs

While making changes to #207 I noticed we are also using `Option<String>` as the parameter type for `default_value` setters (just as we did for description setters). This PR changes the parameter type to `String`.

feat(apollo-encoder): default setters accept String as parameter

---

crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/queries/database.rs
crates/apollo-compiler/src/queries/values.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/scalars.rs
crates/apollo-compiler/test_data/err/0016_schema_with_built_in_scalar_definition.graphql
crates/apollo-compiler/test_data/err/0016_schema_with_built_in_scalar_definition.txt
crates/apollo-compiler/test_data/err/0017_schema_with_unspecified_scalar.graphql
crates/apollo-compiler/test_data/err/0017_schema_with_unspecified_scalar.txt
crates/apollo-compiler/test_data/err/0018_schema_with_specified_scalar_missing_values.graphql
crates/apollo-compiler/test_data/err/0018_schema_with_specified_scalar_missing_values.txt
crates/apollo-compiler/test_data/ok/0004_schema_with_custom_scalars.graphql
crates/apollo-compiler/test_data/ok/0004_schema_with_custom_scalars.txt

- adds scalars to source database
- creates two new validation errors:
1. "BuiltInScalarDefinition" - when a built in scalar is redefined
2. "ScalarSpecificationURL" - when a custom scalar does not have a specifiedBy directive
closes #233

feat(apollo-compiler): add scalars to compiler's context

---

crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/queries/database.rs
crates/apollo-compiler/src/queries/values.rs
crates/apollo-compiler/src/validation/enums.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/unions.rs
crates/apollo-compiler/test_data/err/0021_union_definition_with_duplicate_members.graphql
crates/apollo-compiler/test_data/err/0021_union_definition_with_duplicate_members.txt
crates/apollo-compiler/test_data/ok/0006_schema_with_valid_union.graphql
crates/apollo-compiler/test_data/ok/0006_schema_with_valid_union.txt

- adds union definitions and union members to source database
- adds validation for unique union member types
- adds a UUID reference to object type for union members
- adds a getter for object type's fields_definition
- adds a getter for field definition name
closes #238

feat(apollo-compiler): add union definitions to source database

---

crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/queries/database.rs
crates/apollo-compiler/src/queries/values.rs
crates/apollo-compiler/src/validation/directives.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/test_data/err/0028_self_referential_directive_definition.graphql
crates/apollo-compiler/test_data/err/0028_self_referential_directive_definition.txt
crates/apollo-compiler/test_data/err/0029_directive_definitions_with_duplicate_names.graphql
crates/apollo-compiler/test_data/err/0029_directive_definitions_with_duplicate_names.txt
crates/apollo-compiler/test_data/ok/0008_schema_with_directive_definition.graphql
crates/apollo-compiler/test_data/ok/0008_schema_with_directive_definition.txt

- adds directive definition to compiler's context
- adds find_directive_definition and find_directive_definition_by_name functions
- adds built-in directives to cumulative directive definitions in compiler (`@include`, `@skip`, `@deprecated`, `@specifiedBy`)
- adds directive definition validations:
- Directive definitions must have unique names (Unique Definition error)
- A directive definition must not contain the use of a directive which references itself directly. (Recursive Definition error)
closes #241

feat(apollo-compiler): add directive definitions to source database

---

crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/queries/database.rs
crates/apollo-compiler/src/queries/values.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/interfaces.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/test_data/err/0030_schema_with_duplicate_input_objects.graphql
crates/apollo-compiler/test_data/err/0030_schema_with_duplicate_input_objects.txt
crates/apollo-compiler/test_data/err/0031_input_object_with_duplicate_fields.graphql
crates/apollo-compiler/test_data/err/0031_input_object_with_duplicate_fields.txt
crates/apollo-compiler/test_data/ok/0009_schema_with_input_object.graphql
crates/apollo-compiler/test_data/ok/0009_schema_with_input_object.txt

- adds input object values
- adds validation for unique input object definition and unique input fields in input object
related to #247

feat(apollo-compiler): add input object definitions to source database

---

crates/apollo-encoder/src/field.rs
crates/apollo-encoder/src/fragment.rs
crates/apollo-encoder/src/selection_set.rs
crates/apollo-smith/src/description.rs
crates/apollo-smith/src/name.rs
fuzz/.gitignore
fuzz/Cargo.toml

switches all `str.push_str(format!())` usecases to `write!()` instead (#[warn(format_push_string)])

chore: make clippy happy and avoid extra allocations

---

crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/queries/database.rs
crates/apollo-compiler/src/queries/values.rs
crates/apollo-compiler/src/validation/unused_variables.rs

We want to be able to have access to type information in an executable definitions, i.e. tie schema information to query information. This PR introduces some basic relationships for more straightforward selection sets. A given `Field` now has both the `reference_ty_id` and `ty` information when available. This makes it possible to have access to schema-defined types.

feat(apollo-compiler): add field types to operation definitions

---

crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/queries/values.rs

Currently it's impossible to get at `ObjectTypeDefinition::directives`

Add an accessor for `directives` on `ObjectTypeDefinition`

---

crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/queries/database.rs
crates/apollo-compiler/src/queries/values.rs
crates/apollo-compiler/src/validation/operations.rs
crates/apollo-compiler/src/validation/unused_variables.rs

Fragment definitions now keep a reference to their type in a given schema. This means that we can find type information on any field in a fragment definition.

feat(apollo-compiler): add type information to fragment definition's fields

---

.circleci/config.yml

this is the latest stable xcode build, 11.4 is no longer supported and builds are failing

chore: update to xcode 13.4

---

crates/apollo-parser/src/lexer/mod.rs
crates/apollo-parser/src/parser/grammar/argument.rs
crates/apollo-parser/src/parser/grammar/value.rs
crates/apollo-parser/test_data/parser/err/0031_argument_with_erronous_string_value.txt
crates/apollo-parser/test_data/parser/err/0033_directive_with_erronous_string_value.txt
crates/apollo-parser/test_data/parser/err/0034_directive_with_unfinished_string_value.graphql
crates/apollo-parser/test_data/parser/err/0034_directive_with_unfinished_string_value.txt

I don't know if it's the right way to fix it, but we already have this kind of issues with value if we don't pop error so I added a parameter to pop the token if needed to not have an infinite loop again there.
close #266

fix(lexer,parser): do not run in infinite loop when we're in an unclosed string value

---

crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/queries/database.rs
crates/apollo-compiler/src/queries/values.rs
crates/apollo-encoder/src/fragment.rs
crates/apollo-encoder/src/string_value.rs
crates/apollo-parser/src/lexer/token_kind.rs
crates/apollo-smith/src/operation.rs

Inline fragments were missing type correct type information. We now search for applicable type's fields if a type condition exists, otherwise infer information from the current type in scope ([as per spec](https://spec.graphql.org/October2021/#sel-GAFbfJABAB_F3kG )).
This also adds a few ease-of-use getters for getting all inline_fragments from a selection set, and changes inline_fragment's type_condition getter to return `Option<&str>`. Previously returned `Option<&String>` was a bit less friendly to use.
Thank you for @lennyburdette for the test cases!
Fixes #280

fix(apollo-compiler): add type information to inline fragments

---

crates/apollo-compiler/src/queries/database.rs
crates/apollo-compiler/src/queries/values.rs
crates/apollo-compiler/test_data/ok/0011_fragment_spreads_in_fragment_definitions.graphql
crates/apollo-compiler/test_data/ok/0011_fragment_spreads_in_fragment_definitions.txt
crates/apollo-compiler/test_data/ok/0012_introspection_query.graphql
crates/apollo-compiler/test_data/ok/0012_introspection_query.txt

because fragment definitions can have fragment spreads, we are running into a self-referential cycle when searching for a fragment definition to get its id. Instead, search for the fragment definition when getting a fragment in a fragment spread in the wrapper API.
Adds tests for nested fragments, and an introspection query, where this bug has initially arisen.
closes #281

fix(apollo-compiler): do not add fragment_id to fragment_spread

---

crates/apollo-parser/src/parser/grammar/operation.rs
crates/apollo-parser/test_data/parser/err/0040_operation_definition_missing_selection_set.graphql
crates/apollo-parser/test_data/parser/err/0040_operation_definition_missing_selection_set.txt
crates/apollo-parser/test_data/parser/err/0041_operation_definition_with_missing_selection_set.graphql
crates/apollo-parser/test_data/parser/err/0041_operation_definition_with_missing_selection_set.txt

The parser was not creating errors for missing selection sets. fixes #300

fix(parser): selection set is required for named operation definitions

---

crates/apollo-compiler/README.md
crates/apollo-compiler/examples/hello_world.rs
crates/apollo-compiler/src/database/ast.rs
crates/apollo-compiler/src/database/db.rs
crates/apollo-compiler/src/database/def.rs
crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/inputs.rs
crates/apollo-compiler/src/database/mod.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/tests.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/directives.rs
crates/apollo-compiler/src/validation/enum_.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/object.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/scalar.rs
crates/apollo-compiler/src/validation/schema.rs
crates/apollo-compiler/src/validation/union_.rs
crates/apollo-compiler/src/validation/unused_variable.rs

Validation was its own module, which isn't as useful as having it be a salsa query group! We can now take advantage of memoised validation functions, as well as have a more succinct RootDatabase.
In this process, we've also renamed all query groups to match their associated storage names, as well as add `Database` to their naming. This ensures there is no confusion to `Document` or `Definition` being confused with ast's document or definition for the code reader. 
To allow `ValidationDatabase` to continue making calls to specific queries in `DocumentDatabase`, we've also added an `Upcast` trait.

refactor(compiler): create a validation database

---

crates/apollo-compiler/src/database/hir.rs

There is currently no way to return the directives from a `FragmentSpread` definition, this PR adds one in the same manner that `InlineFragment` does.

Expose directives from FragmentSpread types

---

crates/apollo-parser/src/parser/grammar/document.rs
crates/apollo-parser/src/parser/grammar/selection.rs
crates/apollo-parser/test_data/parser/err/0042_document_with_incorrect_token.graphql
crates/apollo-parser/test_data/parser/err/0042_document_with_incorrect_token.txt

Unhandled tokens directly inside a document would break the loop in the parser. This resulted in the rest of the parsing to be skipped. An error would be expected here instead.

fix(apollo-parser): handle unexpected tokens in document

---

crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/src/directive_def.rs
crates/apollo-encoder/src/fragment.rs
crates/apollo-encoder/src/from_parser.rs
crates/apollo-encoder/src/lib.rs

Provides `TryFrom` impls for the apollo-encoder AST types.
The conversion effectively assumes that the apollo-parser AST is valid and complete. Otherwise you get an Err, but not a very useful one, because the TryFrom impl doesn't know anything about its parent (so we can't show source code where the error originated for example).
I put it behind a feature flag so apollo-encoder doesn't *have* to depend on apollo-parser, not sure if that is truly worth it, so i also enabled it by default 😛 .

feat(encoder): provide TryFrom<parser types> for encoder types

---

crates/apollo-compiler/Cargo.toml

I assume this was a typo. Caused warnings like:
```
warning: crates/apollo-compiler/Cargo.toml: unused manifest key: dependencies.apollo-parser.apollo-parser
```

fix(compiler): fix apollo-parser dependency version

---

crates/apollo-compiler/Cargo.toml
crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/src/from_parser.rs

uses `.source_string()` instead of the previously applicable `Display`

chore(encoder): upgrade to apollo-parser@0.3.0

---

crates/apollo-compiler/src/lib.rs

Uses `ParallelDatabase` snapshot type instead of `Storage` snapshot type. This allows us to query a database snapshot in a multithreaded environment.

fix(compiler): use correct snapshot type

---

crates/apollo-encoder/Cargo.toml
crates/apollo-parser/Cargo.toml
crates/apollo-parser/examples/modify_query_using_parser_and_encoder.rs

A few folks have been trying to modify/generate new schemas and queries using the AST provided with the parser. Given changes in #329, it's a bit easier generating SDL with the encoder using `ast_type.try_from()?`. 
This example outlines two possible modifications:
- merging two queries
- omitting certain fields in a query.

docs(parser): example of modifying queries with parser + encoder

---

crates/apollo-parser/src/parser/mod.rs

A little simplification 😇 
We're inside `bump_ignored()` here, and `bump()` calls `bump_ignored()` again internally. So this loop didn't really do a lot: we end up doing just one iteration in the loop and recursing into `bump_ignored()` again to eat the next token.
Using `eat()` here is equivalent but without the recursion.

chore(parser): use `eat` in a loop instead of recursing `bump`

---

crates/apollo-compiler/src/database/hir.rs

The previous pattern of `db.find_object_type(op.object_type_id(db)?)` would first find an `ObjectTypeDefinition` by its name, extract its UUID, then find the same `ObjectTypeDefinition` again by its UUID. The last step is redundant.
This adds a `RootOperationTypeDefinition::object_type` public API. It could be private, but it seems reasonable to make public since `object_type_id` is already public.

chore(compiler): Avoid double lookup in `SchemaDefinition::query/mutation/subscription`

---

crates/apollo-compiler/src/database/hir_db.rs

Directive locations for the `@include` directive should include FragmentSpread as a location and not FragmentDefinition. Updating injected directive to match expectation.

Fix injected `@include` directive locations to match spec

---

crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-encoder/src/from_parser.rs
crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/src/ast/node_ext.rs
crates/apollo-parser/src/parser/grammar/value.rs
crates/apollo-smith/CHANGELOG.md
crates/apollo-smith/Cargo.toml
crates/apollo-smith/src/argument.rs
crates/apollo-smith/src/directive.rs
crates/apollo-smith/src/document.rs
crates/apollo-smith/src/enum_.rs
crates/apollo-smith/src/field.rs
crates/apollo-smith/src/fragment.rs
crates/apollo-smith/src/input_object.rs
crates/apollo-smith/src/input_value.rs
crates/apollo-smith/src/interface.rs
crates/apollo-smith/src/lib.rs
crates/apollo-smith/src/object.rs
crates/apollo-smith/src/operation.rs
crates/apollo-smith/src/scalar.rs
crates/apollo-smith/src/schema.rs
crates/apollo-smith/src/selection_set.rs
crates/apollo-smith/src/union.rs

This PR changes the `From<$ParserNode> for $RustType` implementations to `TryFrom`, so that user input cannot cause panics as easily. For example, `i32::from(node)` could panic if `node` contains a very large integer.
This PR also adds an `impl TryFrom<IntValue> for f64` implementation, as you are allowed to write integers when a schema expects a float.
closes #358
These are still todos but could be done later:

feat(parser,smith): make the conversions to native types fallible

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/test_data/ok/0014_float_values.graphql
crates/apollo-compiler/test_data/ok/0014_float_values.txt

Previously the HIR stored an `i32` for values with integer syntax, restricting the supported range if the value ended up used as a `Float`.
Now it stores `f64` for all numeric literals (though still with `Int` and `Float` variants). Coercion to `Int` is a separate fallible method.

Add coercion of hir::Value::Int to Float input value without losing precision

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-parser/src/parser/grammar/field.rs
crates/apollo-parser/src/parser/grammar/ty.rs
crates/apollo-parser/src/parser/mod.rs
crates/apollo-parser/test_data/parser/err/0043_type_with_trailing_garbage.graphql
crates/apollo-parser/test_data/parser/err/0043_type_with_trailing_garbage.txt
crates/apollo-parser/test_data/parser/err/0044_list_type_with_no_type.graphql
crates/apollo-parser/test_data/parser/err/0044_list_type_with_no_type.txt

Ref #256, probably not a *full* fix yet, but that issue is quite broad.
I set out to simply change every panic in HIR creation to returning a `None`, but while writing tests I triggered panics in the parser, so I tried to address those too.
- This removes some panics from type name parsing. For example, `field: []` does not panic anymore. Instead it produces a syntax error and an incomplete List type.
- Fixes the parser completely bailing out of parsing a list of field definitions when encountering a syntax error in one field.
```graphql
type A {
fieldA: [] # ← has error, missing item type
fieldB: Int
fieldC: Int
}
```
Previously fieldB and fieldC would not be parsed, now they are.
- Replaces panics when creating the HIR with `Option`s. This means that AST nodes with errors are *ignored* …

fix(compiler,parser): do not panic during HIR creation

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/examples/hello_world.rs
crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/enum_.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/object.rs
crates/apollo-compiler/src/validation/scalar.rs
crates/apollo-compiler/src/validation/union_.rs
crates/apollo-compiler/src/validation/validation_db.rs

* For all kinds of definitions that have a mandatory name, keep them in source-order-preserving `IndexMap` instead of a `Vec` to speed up name lookup.
* Remove type extensions as independent HIR items, instead store them in a new `extensions` struct field on the respective definitions they extend.
* Wrap more HIR components in Arc, to reduce cost of Salsa’s cloning.

feat(compiler): Name-indexed maps + inlined extensions

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs

Refering to a particular definition can be done by its name, which is expected to be unique.

Remove UUIDs from the HIR

---

crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/union_.rs
crates/apollo-compiler/src/validation/validation_db.rs
crates/apollo-compiler/test_data/diagnostics/0036_object_type_with_non_output_field_types.txt
crates/apollo-compiler/test_data/diagnostics/0037_interface_with_non_output_fields.txt

* Split `hir::Definition` enum variants that define types into a new `NamedTypeDefinition` enum.
* Add Salsa queries for finding a type by its name, (excluding non-type named definitions), and use them where appropriate. This changes some diagnostics from "wrong definition kind" to "no such type".
* Remove `find_type_system_definition_by_name` and `find_definition_by_name` queries since they mix up the four namespaces of a GraphQL document that should really be separate. Instead its callers should probably use one of:
* `find_directive_definition_by_name`
* `find_operation_by_name`
* `find_fragment_by_name`
* `find_type_definition_by_name`

Move named types to a separate HIR enum and separate namespacing

---

crates/apollo-compiler/README.md
crates/apollo-compiler/examples/extend_db.rs
crates/apollo-compiler/src/database/db.rs
crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/database/mod.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/validation_db.rs

This allows HIR construction for e.g. selection sets to use higher-level queries such as finding a type definition by name (which is now backed by a memoized map instead of linear search)
Relevant query implementations are left in `document.rs` because `hir_db.rs` is already 1.5k lines.

Merge `DocumentDatabase` into `HirDatabase`

---

crates/apollo-parser/benches/query.rs
crates/apollo-parser/benches/testdata/alias.graphql

https://github.com/apollographql/apollo-rs/issues/293#issue-1367277482
Adds a benchmark for a query identified to parse more slowly than expected given the overall size of the query. Extracted from https://github.com/apollographql/apollo-rs/pull/322 which attempts to improve this benchmark by eliminating string allocations during lexing.
This query is based on a pattern seen in production, I suspect there are GraphQL clients that generate queries with many aliases as a form of aggregation or batching.

Adds benchmark for nested aliased query type

---

crates/apollo-smith/src/argument.rs
crates/apollo-smith/src/description.rs
crates/apollo-smith/src/directive.rs
crates/apollo-smith/src/field.rs
crates/apollo-smith/src/fragment.rs
crates/apollo-smith/src/input_object.rs
crates/apollo-smith/src/input_value.rs
crates/apollo-smith/src/interface.rs
crates/apollo-smith/src/name.rs
crates/apollo-smith/src/object.rs
crates/apollo-smith/src/operation.rs
crates/apollo-smith/src/scalar.rs
crates/apollo-smith/src/schema.rs
crates/apollo-smith/src/selection_set.rs
crates/apollo-smith/src/ty.rs
crates/apollo-smith/src/union.rs
crates/apollo-smith/src/variable.rs

fixes https://github.com/apollographql/apollo-rs/issues/388
I think renaming or writing out `arbitrary::Result` is better here than aliasing `arbitrary::Result` to the name thats already in the rust prelude. I accidentally used the wrong `Result` type because of the name collision.

chore(smith): avoid using arbitrary::Result where std Result is intended

---

README.md
crates/apollo-compiler/README.md
crates/apollo-encoder/README.md
crates/apollo-parser/README.md
crates/apollo-smith/README.md

In the root readme to be visible on the repo’s home page on github, and repeated in crate-specific readmes to be visible on crates.io

Document that only latest Stable Rust is supported

---

crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/database/inputs.rs

We don't need to store these queries in salsa's cache, so annotate them with `#[salsa::transparent]` and compute them when necessary.
Closes #373

fix(compiler): use #[salsa::transparent] for all find_ queries

---

crates/apollo-compiler/examples/extend_db.rs
crates/apollo-compiler/src/database/sources.rs
crates/apollo-compiler/src/lib.rs

When we add an alternative kind of compiler input that contains already-parsed HIR nodes, this will allows `FileId` in these nodes to stay meaningful across multiple compiler instances in the same address space.

feat(compiler): make `FileId`s unique per-process

---

crates/apollo-compiler/src/lib.rs

This allows naming the return type of `ApolloCompiler::snapshot` without importing `salsa` separately.

feat(compiler): add type alias for `compiler.snapshot()`

---

crates/apollo-compiler/README.md
crates/apollo-compiler/benches/multi_source.rs
crates/apollo-compiler/examples/file_watcher.rs
crates/apollo-compiler/examples/hello_world.rs
crates/apollo-compiler/examples/multi_source_validation.rs
crates/apollo-compiler/src/database/ast.rs
crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/tests.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/object.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/unused_variable.rs

Methods of `ApolloCompiler`:
* `create_document` → `add_document`
* `create_schema` → `add_schema`
* `create_executable` → `add_executable`
As discussed in https://github.com/apollographql/apollo-rs/pull/407#discussion_r1064512416

breaking(compiler): rename create_* methods to add_*

---

crates/apollo-compiler/README.md
crates/apollo-compiler/benches/multi_source.rs
crates/apollo-compiler/examples/multi_source_validation.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/lib.rs

For consistency with https://github.com/apollographql/apollo-rs/pull/407 and avoiding confusion with `compiler.db.schema()` which returns a `SchemaDefinition`.

breaking(compiler): rename `{add,update}_schema` to `*_type_system`

---

crates/apollo-compiler/src/database/ast.rs
crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/database/inputs.rs
crates/apollo-compiler/src/database/sources.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/object.rs

This allows extracting a parsed type system from Salsa
into read-only data that can be shared across threads,
with each thread using it as input to new compiler instances.
Fixes https://github.com/apollographql/apollo-rs/issues/406

feat(compiler): introduce pre-computed type system input

---

crates/apollo-smith/src/document.rs
crates/apollo-smith/src/field.rs
crates/apollo-smith/src/fragment.rs
crates/apollo-smith/src/operation.rs
crates/apollo-smith/src/scalar.rs
crates/apollo-smith/src/selection_set.rs
crates/apollo-smith/src/union.rs
crates/apollo-smith/src/variable.rs

Cloning `Document` enables calling `DocumentBuilder::with_document` multiple times without reparsing.

feat(smith): derive Clone for most types

---

crates/apollo-smith/src/lib.rs

This indicates we might have run into https://github.com/rust-fuzz/arbitrary/issues/139

feat(smith): add DocumentBuilder::input_exhausted

---

crates/apollo-compiler/README.md
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/validation_db.rs
crates/apollo-compiler/test_data/diagnostics/0031_input_object_with_duplicate_fields.txt
crates/apollo-compiler/test_data/diagnostics/0040_operation_with_undefined_fields_on_reference_type.graphql
crates/apollo-compiler/test_data/diagnostics/0040_operation_with_undefined_fields_on_reference_type.txt
crates/apollo-compiler/test_data/diagnostics/0046_duplicate_directive_arguments.graphql
crates/apollo-compiler/test_data/diagnostics/0046_duplicate_directive_arguments.txt
crates/apollo-compiler/test_data/diagnostics/0050_directives_in_invalid_locations.graphql
crates/apollo-compiler/test_data/diagnostics/0050_directives_in_invalid_locations.txt
crates/apollo-compiler/test_data/diagnostics/0051_undefined_directive.graphql
crates/apollo-compiler/test_data/diagnostics/0051_undefined_directive.txt
crates/apollo-compiler/test_data/ok/0010_operation_with_defined_fields.graphql
crates/apollo-compiler/test_data/ok/0010_operation_with_defined_fields.txt
crates/apollo-compiler/test_data/ok/0015_supergraph.graphql
crates/apollo-compiler/test_data/ok/0015_supergraph.txt

partial of #246
This looks over each directive usage and checks whether it's in a correct location as specified by its original DirectiveDefinition. In case of incorrect usage `UnsupportedLocation` error is returned. Since we are already looking for the original DirectiveDefinition, this PR also adds a `UndefinedDefinition` error for undefined directives in case that DirectiveDefinition is not found.
While working on this validation rule, I realised we need to tidy up our ValidationDatabase before we implement any follow up rules. Primarily we are using two different paths for validating: `check_*` and `validate_*`, which should be unified in some way. 
We are also creating a lot of `let diagnostics = Vec::new()` for pretty much each validation step, and it would be good to not keep …

feat(compiler): validate directive locations + undefined directives

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/validation_db.rs
crates/apollo-compiler/test_data/diagnostics/0050_directives_in_invalid_locations.txt

Noticed a small improvement opportunity while merging `main` into #414…
`OperationType` already has a `Display` impl, so we don't actually need a separate `Into<String>`: users can do `ty.to_string()` and it will use `Display`.
`DirectiveLocation` also has a `Into<String>` impl. If we use a `Display` impl instead, we can print `DirectiveLocation`s directly in format strings. Then we can also just stick the `DirectiveLocation` value into our diagnostics, instead of stringifying them first, which makes the diagnostic more programmatically useful.

chore(compiler): use Display impls for OperationType, DirectiveLocation

---

crates/apollo-compiler/src/database/sources.rs
crates/apollo-compiler/src/tests.rs

This feels a little janky, but should make the issue with File IDs that we are running into in #414 much less urgent. By resetting file IDs before scanning a directory for file-based tests we get a consistent order each time, and adding tests to 1 directory doesnt increment every file ID in another directory.
The `FileId::reset()` api is not public here, we can see if the router ends up needing it for some tests too or if at that point we should consider other approaches. for now this is the simplest change I can think of to make the `expect` based tests work well enoguh.

Reset FileId between directory tests

---

crates/apollo-encoder/src/from_parser.rs
crates/apollo-encoder/src/lib.rs

otherwise we cannot build upon the TryFrom implementation with apollo-parser types

make FromError public

---

crates/apollo-compiler/src/database/ast.rs
crates/apollo-compiler/src/database/hir_db.rs

Noticed some minor clippy warnings when opening my previous PR. 
```
warning: useless conversion to the same type: `std::slice::Iter<'_, apollo_parser::Error>`
--> crates/apollo-compiler/src/database/ast.rs:47:13
|
47 | /             db.ast(file_id)
48 | |                 .errors()
49 | |                 .into_iter()
| |____________________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
= note: `#[warn(clippy::useless_conversion)]` on by default
help: consider removing `.into_iter()`
|
47 ~             db.ast(file_id)
48 +                 .errors()
|
warning: useless conversion to the same type: `apollo_parser::ast::AstChildren<apollo_parser::ast::EnumValueDefinition>`
--> …
```

fix clippy warnings related to unnecessary into_iter

---

crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/enum_.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/object.rs
crates/apollo-compiler/src/validation/union_.rs

Part of https://github.com/apollographql/apollo-rs/issues/468, for components that have a unique name such as fields of object types.
Internally, `IndexMap` is used to map names to `Vec` indices.
Renamed:
* `ObjectTypeDefinition::fields_definition` → `self_fields`
* `ObjectTypeDefinition::implements_interfaces` → `self_implements_interfaces`
* `InterfaceTypeDefinition::fields_definition` → `self_fields`
* `InterfaceTypeDefinition::implements_interfaces` → `self_implements_interfaces`
* `InputObjectTypeDefinition::input_fields_definition` → `self_fields`
* `UnionTypeDefinition::union_members` → `self_members`
* `EnumTypeDefinition::enum_values_definition` → `self_values`
Names freed by the above, redefined with new behavior (to consider extensions) and signature:
* …

feat(compiler): implicit extensions in HIR uniquely-named-item APIs

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/schema.rs
crates/apollo-compiler/test_data/diagnostics/0059_root_operation_object_type.txt
crates/apollo-compiler/test_data/diagnostics/0060_root_operation_definition_undefined_operation_type.txt
crates/apollo-compiler/test_data/diagnostics/0061_root_operation_with_default_undefined_query.txt

A collection of loosely related changes, part of https://github.com/apollographql/apollo-rs/issues/468.
HIR no longer creates an implicit root operation if an explicit one exists in a schema extension, even if an object type named `Query`/`Mutation`/`Subscription` exists and the base schema definition doesn’t define an explicit root operation of that type.
`SchemaDefinition::root_operation_type_definition()` was renamed to `self_root_operations`.
`SchemaDefinition::root_operations() -> impl Iterator` was added. It includes root operations from extensions.
`SchemaDefinition::query()`, `mutation()`, and `subscription()` now account for schema extensions, and return `Option<&str>` with the name instead of the definition of the corresponding object type. That definition can be found at …

feat(compiler): implicit extensions in HIR root operation APIs

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/test_data/ok/0024_used_variables_in_directives.graphql
crates/apollo-compiler/test_data/ok/0024_used_variables_in_directives.txt

Operations can use variables in two places: field arguments and directive arguments. Previously we only counted field arguments, so we'd raise an error on things like this:
```graphql
query ($var: Boolean) {
field @skip(if: $var)
}
```
This PR correctly counts `$var` as used.

fix(compiler): fix variables in directive arguments being reported as unused

---

crates/apollo-compiler/src/database/ast.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/database/inputs.rs

Using `salsa::invoke` to indicate where the function comes from in our `hir_db`. Makes it _soooo_ much easier to click through to the function definition and just to read where the function is.

chore(compiler): use salsa invoke for ease of navigating

---

crates/apollo-compiler/src/database/hir.rs

This type resolution in https://github.com/apollographql/router/issues/2710 was the motivation to start work on
https://github.com/apollographql/apollo-rs/issues/468

Add a test for operation field type resolution v.s. type extensions

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs

Like built-in object types are included. This is consistent with the implicit input for built-in types being skipped when using set_type_system_hir()

Include built-in enum types in db.type_system()

---

crates/apollo-compiler/src/database/ast.rs
crates/apollo-compiler/src/database/inputs.rs
crates/apollo-compiler/src/lib.rs

Adding the token API that already works nicely in the parser to the compiler. This *breaks* the current recursion_limit API we have in the compiler, but hopefully makes it a lot more ergonomic in terms of usage.
Here is how you'd set both limits:
```rust
let schema = r#"
query {
a {
a {
a {
a
}
}
}
}
"#;
let mut compiler = ApolloCompiler::new().token_limit(22).recursion_limit(10);
compiler.add_document(schema, "schema.graphql");
```
closes #509

breaking(compiler): add parser's token limiting to compiler's API

---

crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/test_data/diagnostics/0079_directive_is_unique.txt
crates/apollo-compiler/test_data/diagnostics/0080_directive_is_unique_with_extensions.txt
crates/apollo-compiler/test_data/diagnostics/0081_directive_is_unique_type_system.txt

fix(compiler): Fix duplicate directive validation location information

---

crates/apollo-encoder/src/directive_def.rs
crates/apollo-encoder/src/document.rs
crates/apollo-encoder/src/fragment.rs
crates/apollo-encoder/src/object_def.rs
crates/apollo-encoder/src/operation.rs
crates/apollo-encoder/src/variable.rs

Noticed that `Clone` was derived on some but not all encoder types when I tried to `.clone()` an `encoder::ObjectDefinition` instance. 
Not sure if there's a good reason, but ahead and opened this PR if it just happened to be an omission.

chore(encoder): add missing clone impl to encoder types

---

crates/apollo-compiler/examples/validate.rs

Just a way to run all the validations on a single file.
I found this quite useful just to check the output of a single test_data file or to try things out separate of our tests. You can do:
```
cargo run --example validate path/to/document.graphql
```

feat: add a validation executable

---

crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/object.rs
crates/apollo-compiler/src/validation/validation_db.rs
crates/apollo-compiler/test_data/diagnostics/0094_object_type_extensions.graphql
crates/apollo-compiler/test_data/diagnostics/0094_object_type_extensions.txt
crates/apollo-compiler/test_data/diagnostics/0095_interface_implementation_declared_once.graphql
crates/apollo-compiler/test_data/diagnostics/0095_interface_implementation_declared_once.txt

Closes https://github.com/apollographql/apollo-rs/issues/476
Progress:
[spec](https://spec.graphql.org/October2021/#sec-Object-Extensions.Type-Validation)

feat(compiler): validate object type extensions

---

crates/apollo-compiler/src/validation/enum_.rs
crates/apollo-compiler/test_data/diagnostics/0019_enum_definition_with_duplicate_values.txt
crates/apollo-compiler/test_data/diagnostics/0070_self_referential_directive_definition.graphql
crates/apollo-compiler/test_data/diagnostics/0070_self_referential_directive_definition.txt
crates/apollo-compiler/test_data/diagnostics/0097_enum_extensions.graphql
crates/apollo-compiler/test_data/diagnostics/0097_enum_extensions.txt

New errors for:
- duplicate members
```graphql
enum E { MEMBER_A }
extend enum E { MEMBER_A } # ERROR: the enum value `MEMBER_2` is defined multiple times in the document
```
(the diagnostic message is not ideal there as it's not related to the document, could be improved by adding a DiagnosticData type specifically for enum values)
- duplicate directive applications
```graphql
enum E @nonRepeatable {}
extend enum E @nonRepeatable # ERROR: non-repeatable directive nonRepeatable can only be used once per location
```

feat(compiler): validate enum extensions, fixes #479

---

crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/test_data/diagnostics/0099_input_object_extensions.graphql
crates/apollo-compiler/test_data/diagnostics/0099_input_object_extensions.txt

Currently duplicating `collect_nodes` in every file, will consolidate after the fact.

feat(compiler): validate input object extensions, closes #480

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/examples/modify_query_using_compiler_and_encoder.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/src/from_hir.rs
crates/apollo-encoder/src/lib.rs

Took a shot at implementing these conversion impls. The issue mentioned that the approach required is dependent on some other decisions. Let me know if this aligns with the direction you'd like to take and I'll clean up and add some tests. 
Fixes #424

add TryFrom impls to convert from hir to encoder types (#424)

---

crates/apollo-compiler/src/database/inputs.rs
crates/apollo-compiler/src/database/sources.rs
crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/validation/validation_db.rs
crates/apollo-parser/src/ast/node_ext.rs

This doesn't check the opposite, so you can put executable definitions in a schema document ... the spec doesn't appear to prohibit that as far as I can tell.
we have to check the `source_type` is `SourceType::Executable` before running this check, as `SourceType::Document` sources are also run through this `validate_executable` function.

feat(compiler): validate executable documents do not contain type definitions, fixes #409

---

crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/validation/enum_.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/object.rs
crates/apollo-compiler/src/validation/union_.rs
crates/apollo-encoder/src/from_hir.rs

While merging #428, I noticed some of our extension APIs weren't matching their type definition APIs. For example, `UnionTypeDefinition` has `.members()` API. `UnionTypeExtension`'s version of this API is `.union_members`. 
This PR fixes those inconsistencies.
Changed methods:
- `InputObjectTypeExtension.fields_definition()` -> `InputObjectTypeDefinition.fields()`
- `ObjectTypeExtension.fields_definition()` -> `ObjectTypeExtension.fields()`
- `InterfaceTypeExtension.fields_definition()` -> `InterfaceTypeExtension.fields()`
- `EnumTypeExtension.enum_values_definition()` -> `EnumTypeExtension.values()`
- `UnionTypeExtension.union_members()` -> `UnionTypeExtension.members()`
@SimonSapin tagging you to double check here - i know you did the initial API improvements for `.fields` and …

breaking(compiler): align extension getters to their type def counterparts

---

crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/validation_db.rs

Addresses #543
The core problem is that the `is_introspection` method is not context-aware and if it's in the context of a fragment spread for itself will continue to recurse until the stack overflows. Fundamentally fixing this issue with `is_introspection` would require a some added context like exists with the recursion limit counter in the parser or changing the function signature to control whether or not to recurse into a fragment spread.
I tried to avoid reimplementing fragment definition detection by reusing what already exists and should mean the result is memoized when `validate_fragment_definition` is called during `validate_executable`.
I considered performing fragment definition validation first and skipping operation validation if there are cycles present but there are some …

Prevents recursion for operations referencing fragments with cycles

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/validation/operation.rs

follow-up to https://github.com/apollographql/apollo-rs/pull/544
this moves the possible recursion cases into `SelectionSet::is_introspection` and bails out if a used fragment contains a cycle. For fragments that dont have a definition or that are cyclical, `is_introspection` returns false.
We can keep the tests and the new DB query introduced by #544 :)

fix(compiler): prevent recursion cycle inside is_introspection

---

crates/apollo-parser/src/parser/grammar/variable.rs
crates/apollo-parser/test_data/parser/err/0047_empty_variable_definition.graphql
crates/apollo-parser/test_data/parser/err/0047_empty_variable_definition.txt

fix(parser): variable definitions cannot be empty

---

crates/apollo-compiler/Cargo.toml

apollo-compiler@0.9.0 relies on new apollo-parser methods but didn't declare the correct minimum version.

fix(compiler): update apollo-parser version requirement

---

crates/apollo-compiler/README.md
crates/apollo-encoder/README.md
crates/apollo-parser/README.md

Remove references to cargo-edit.

`cargo add` is now built in

---

crates/apollo-compiler/src/validation/value.rs
crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/test_data/diagnostics/0102_invalid_string_values.txt
crates/apollo-compiler/test_data/ok/0033_valid_variable_usage.graphql
crates/apollo-compiler/test_data/ok/0033_valid_variable_usage.txt

fixes #558 
also noticed a glitch for `null` being provided for a non-nullable input values - those should also error.

fix(compiler): non-nullable variables should be accepted for nullable args

---

crates/apollo-compiler/Cargo.toml

we used a temp crate while waiting for a PR to be released, it's been out for a while now so we can switch to plain ariadne.

chore(compiler): use official ariadne release

---

.github/workflows/github_projects_tagger.yml

This updates a dependency which handles automation of internal team tracking tooling.  The version we were using was merely bit outdated and this repository doesn't have Renovate setup to automatically bump it. 😄   (It doesn't actually change very often.)

chore(deps): Update to github-issue-pull-api-hook@v2.0.1

---

crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/test_data/diagnostics/0040_operation_with_undefined_fields_on_reference_type.txt
crates/apollo-compiler/test_data/diagnostics/0041_subscription_operation_with_undefined_fields.txt
crates/apollo-compiler/test_data/diagnostics/0042_mutation_operation_with_undefined_fields.txt
crates/apollo-compiler/test_data/diagnostics/0082_introspection_types_in_mutation.txt
crates/apollo-compiler/test_data/diagnostics/0083_type_introspection_from_disallowed_type.txt
crates/apollo-compiler/test_data/diagnostics/0088_fragment_selection_set.txt

This adds a bit more context to the "main" error message for
UndefinedField diagnostics. It was already there in the pretty-printed
version but for use cases like an HTTP backend, it's nice to have as
much context as possible in the main message, so it can just dump that
as a JSON string.

feat(compiler): add type name to `UndefinedField` error message

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/validation/selection.rs

As brought up by Sylvain. The comment already talked about concatenation instead of merging. The `merge` name suggests it's doing field merging which is not happening. We may add an actual field merging method in the future.

breaking(compiler): rename `SelectionSet::merge` to `concat`

---

crates/apollo-compiler/Cargo.toml
crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/README.md
crates/apollo-parser/Cargo.toml
fuzz/Cargo.toml

just bumping pretty much everything, except `miette` in apollo-parser and `notify` in apollo-compiler. both are only used in examples and not trivial to update.
would maybe be nice to enable dependabot after 😇  for semver-major updates at least.

dependency updates

---

crates/apollo-encoder/src/schema_def.rs

Per [GraphQL spec](https://spec.graphql.org/draft/#sec-Schema-Extension)
>Schema extensions without additional operation type definitions must not be followed by a { (such as a query shorthand) to avoid parsing ambiguity.
Currently generated definition cannot be parsed by `apollo-compiler`.
```
extend schema @foo {
}
```

fix: schema extension without root fields should skip empty {} block

---

crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/test_data/diagnostics/0052_undefined_directive.txt

Improve the error message so it doesn't say `"cannot find type @directive"`

chore(compiler): separate `UndefinedDirective` diagnostic

---

crates/apollo-parser/src/lexer/mod.rs
crates/apollo-parser/src/parser/mod.rs
crates/apollo-parser/test_data/parser/err/0041_operation_definition_with_missing_selection_set.txt

tl;dr Make consuming the token stream's data produce an identical string to the original input of the lexer.
I was working on a streaming processor using the streaming lexer and noticed that the `Token::Eof` has `"EOF"` as a string hard-coded as it's data. This doesn't appear to be used anywhere (though is maybe a breaking change?) and the tests still pass without this.
The formatter for `Debug` prefixes the location with `EOF` so the debugging output is not effected. The practical effect of this is that __consuming a token stream's data does not produce the same output as the original input.__

Create EOF token with empty data

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/examples/file_watcher.rs

notify v6 doesn't include debounce functionality anymore. There's separate crates for that but its much easier to just use polling instead of the fancy system specific watching implementations & the necessarily leaky abstractions on top of them. So this rewrites and slightly simplifies the `file_watcher` example using notify v6's `PollWatcher`.

chore(examples): update notify to v6

---

crates/apollo-parser/src/lexer/mod.rs
crates/apollo-parser/src/lexer/token.rs

The separate `self.input` check should be unnecessary as the cursor will produce the token now. That's also the only place that used `Token::new` and `self.input` so we can remove that constructor + the `input`/`index` fields in the Lexer struct (that is tracked in Cursor as well).
Closes https://github.com/apollographql/apollo-rs/issues/610

chore(parser): test reaching token limit exactly

---

crates/apollo-encoder/CHANGELOG.md
crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/README.md
crates/apollo-parser/Cargo.toml
crates/apollo-smith/Cargo.toml

it's a bit annoying that we have to release this every time we have a new parser or compiler version. It will get easier with the MIR work being directly serializable :)

apollo-encoder@0.7.0

---

crates/apollo-smith/CHANGELOG.md
crates/apollo-smith/Cargo.toml

just dependency bumps, apollo-smith is somewhat outdated so the router has different versions of parser/encoder in its dep tree.

apollo-smith@0.4.0

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/src/lexer/mod.rs

This is the most basic fix for #632, but there are other parse bugs left that may be we should address with a bunch more tests. This fixes a regression in apollo-parser 0.6.0.
Block strings are not meant to support escape sequences in general. But the lexer handled strings and block strings the same way, so an invalid escape sequence in a block string 
would cause a lex error. This rips out all the escape sequence handling from block strings except for `\"""`.
I'm running it through the corpus of Apollo schemas right now, about 75% done without problems, so it looks good.

fix(parser): fix lexing escape sequences in block strings

---

crates/apollo-compiler/examples/extract_directives_used_by_query.rs

Added a silly example showing how one can use the apollo_compiler crate to extract directives used by a given query. I had to do something similar for my day job and figured I'd share the love :)  Fixes #636

chore(compiler): add directive extraction example

---

crates/apollo-parser/Cargo.toml
crates/apollo-parser/src/ast/node_ext.rs
crates/apollo-parser/src/parser/grammar/description.rs
crates/apollo-parser/src/parser/grammar/value.rs

Follow-up to #638, fixing conversion of StringValue nodes to Rust strings.
Fixes #609
Fixes #611
This handles
This does not handle these unicode escape issues:
- https://github.com/apollographql/apollo-rs/issues/608
- https://github.com/apollographql/apollo-rs/issues/640

fix(parser): fix some escape sequences in strings and indentation in block strings

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/tests.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/src/validation/fragment.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/selection.rs
crates/apollo-compiler/src/validation/validation_db.rs
crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/test_data/diagnostics/0003_anonymous_and_named_operation.txt
crates/apollo-compiler/test_data/diagnostics/0028_interface_definition_with_missing_fields_implements_intrefaces_undefined_interfaces.txt
crates/apollo-compiler/test_data/diagnostics/0035_object_type_definition_with_missing_implements_interfaces_definition.txt
crates/apollo-compiler/test_data/diagnostics/0036_object_type_with_non_output_field_types.txt
crates/apollo-compiler/test_data/diagnostics/0037_interface_with_non_output_fields.txt
crates/apollo-compiler/test_data/diagnostics/0039_interface_with_undefined_field_type.txt
crates/apollo-compiler/test_data/diagnostics/0050_directives_in_invalid_locations.txt
crates/apollo-compiler/test_data/diagnostics/0053_argument_name_is_not_defined.txt
crates/apollo-compiler/test_data/diagnostics/0054_argument_not_provided.txt
crates/apollo-compiler/test_data/diagnostics/0074_merge_identical_fields.txt
crates/apollo-compiler/test_data/diagnostics/0078_merge_conflict_nested_fragments.txt
crates/apollo-compiler/test_data/diagnostics/0080_directive_is_unique_with_extensions.txt
crates/apollo-compiler/test_data/diagnostics/0081_directive_is_unique_type_system.txt
crates/apollo-compiler/test_data/diagnostics/0087_fragment_type_condition_on_composite_types.txt
crates/apollo-compiler/test_data/diagnostics/0089_fragment_type_condition_on_non_existent_types.txt
crates/apollo-compiler/test_data/diagnostics/0090_fragment_spread_impossible.txt
crates/apollo-compiler/test_data/diagnostics/0095_interface_implementation_declared_once.txt
crates/apollo-compiler/test_data/diagnostics/0102_invalid_string_values.txt

Fixes #629 
This adds a `compiler.db.validate_standalone_executable(file_id)` function that only runs those validations that do not require a schema. Including variable usage, name uniqueness, fragment usage, things like that. I think "standalone" is a decent name but open to bikeshedding.
Also includes a fix for name collisions in executable documents--these actually did not raise an error before.
There are many changes in the test data because this PR sorts the diagnostics by location. There are no changes in the actual diagnostics reported (as test data all uses the validation function that checks against schema.

Support validating standalone operations without a known schema

---

crates/apollo-compiler/README.md
crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/test_data/diagnostics/0002_multiple_anonymous_operations.txt
crates/apollo-compiler/test_data/diagnostics/0003_anonymous_and_named_operation.txt
crates/apollo-compiler/test_data/diagnostics/0040_operation_with_undefined_fields_on_reference_type.txt
crates/apollo-compiler/test_data/diagnostics/0042_mutation_operation_with_undefined_fields.txt
crates/apollo-compiler/test_data/diagnostics/0056_variables_are_input_types.txt
crates/apollo-compiler/test_data/diagnostics/0083_type_introspection_from_disallowed_type.txt
crates/apollo-compiler/test_data/diagnostics/0103_invalid_type_in_arg.graphql
crates/apollo-compiler/test_data/diagnostics/0103_invalid_type_in_arg.txt
crates/apollo-compiler/test_data/ok/0003_schema_definition_with_custom_operation_types.graphql
crates/apollo-compiler/test_data/ok/0003_schema_definition_with_custom_operation_types.txt
crates/apollo-compiler/test_data/ok/0010_operation_with_defined_fields.graphql
crates/apollo-compiler/test_data/ok/0010_operation_with_defined_fields.txt

This is a pretty big thing that we missed until now, so I added it to the current validation implementation. Obviously will
also address this in the validation on top of the new AST. Found by @o0Ignition0o \ 😄 /
Input values (in `input object` declarations and in argument declarations) did not have full validation. Only their names were checked, but if you declared a `arg: NonExistentType`, it would happily truck on.
This PR checks that the declared type exists, and is an input type. If you declare an input value or argument with an output type, you get an error.
As a small cleanliness refactor, this moves the object field output type validation into `validate_field_definition`, as it doesn't need context about other fields in a type definition.
The input type validations for variables …

fix(compiler): validate input value types

---

crates/apollo-compiler/CHANGELOG.md

[chglg](https://github.com/apollographql/apollo-rs/blob/334956bcb6c818ab45111080384002d600b00e04/crates/apollo-compiler/CHANGELOG.md)
I omitted `validate_standalone_executable` from the changelog for now, I want to ensure it does everything it can before we properly announce it. Trying to do as much of that during the port to new AST/HIR. But it is part of the release in case rover will use it.

apollo-compiler@0.11.2

---

crates/apollo-compiler/src/ast/from_cst.rs
crates/apollo-compiler/src/ast/impls.rs
crates/apollo-compiler/src/ast/mod.rs
crates/apollo-compiler/src/ast/serialize.rs
crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/validation/value.rs

Rather converting to i32 or f64 during parsing, we preserve the parsed token as-is. Conversion is left for input value coercion, when the expected type is known (`Float`, `Int`, `ID`, custom scalar, …)

Introduce ast::IntValue and FloatValue containing a String

---

crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/fragment.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/mod.rs

Now that this is only used with the new `NodeStr` type, it's wasteful and inconvenient to have it use String instances.
Also split it into `RecursionStack`/`RecursionGuard` types so you can't write something that has lifetime errors as easily, and so you don't have to create your own vec for storage.

chore(compiler): rewrite RecursionStack to avoid copies to String

---

crates/apollo-compiler/src/schema/component.rs
crates/apollo-compiler/src/schema/from_ast.rs
crates/apollo-compiler/src/schema/mod.rs
crates/apollo-compiler/src/schema/serialize.rs
crates/apollo-compiler/src/validation/fragment.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/tests/merge_schemas.rs
fuzz/fuzz_targets/reparse.rs

`Component<T>` and `ComponentStr` now compare equal based on their content, without considering anymore whether they come from a definition or an extension.
Because `ExtensionId` is an arbitrary integer, parsing the same SDL twice yields different IDs. This would cause the two `Schema` structs not to compare equal, which made it impossible to use the invariant "serializing and reparsing gives the same tree" for fuzzing.
Additionally, instances of `IndexMap<NodeStr, ComponentOrigin>` have been simplified to the now-equivalent `IndexSet<ComponentStr>`.

Ignore component origin in == and hash, turn some maps into sets

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/schema/from_ast.rs
crates/apollo-compiler/test_data/diagnostics/0107_built_in_directive_double_redefinition.graphql
crates/apollo-compiler/test_data/diagnostics/0107_built_in_directive_double_redefinition.txt
crates/apollo-compiler/test_data/ok/0034_built_in_directive_redefinition.graphql
crates/apollo-compiler/test_data/ok/0034_built_in_directive_redefinition.txt
crates/apollo-compiler/test_data/serializer/diagnostics/0107_built_in_directive_double_redefinition.graphql
crates/apollo-compiler/test_data/serializer/ok/0034_built_in_directive_redefinition.graphql

Fixes https://github.com/apollographql/apollo-rs/issues/656

Allow built-in directives to be redefined

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/schema/from_ast.rs
crates/apollo-compiler/src/schema/mod.rs
crates/apollo-compiler/src/schema/serialize.rs
crates/apollo-compiler/test_data/diagnostics/0063_extension_orphan.txt
crates/apollo-compiler/test_data/diagnostics/0108_implicit_schema_extension.graphql
crates/apollo-compiler/test_data/diagnostics/0108_implicit_schema_extension.txt
crates/apollo-compiler/test_data/ok/0035_implicit_schema_definition_with_query_type.graphql
crates/apollo-compiler/test_data/ok/0035_implicit_schema_definition_with_query_type.txt
crates/apollo-compiler/test_data/ok/0036_implicit_schema_definition_with_several_default_types.graphql
crates/apollo-compiler/test_data/ok/0036_implicit_schema_definition_with_several_default_types.txt
crates/apollo-compiler/test_data/ok/0037_implicit_schema_extension_with_directive.graphql
crates/apollo-compiler/test_data/ok/0037_implicit_schema_extension_with_directive.txt
crates/apollo-compiler/test_data/serializer/diagnostics/0108_implicit_schema_extension.graphql
crates/apollo-compiler/test_data/serializer/ok/0035_implicit_schema_definition_with_query_type.graphql
crates/apollo-compiler/test_data/serializer/ok/0036_implicit_schema_definition_with_several_default_types.graphql
crates/apollo-compiler/test_data/serializer/ok/0037_implicit_schema_extension_with_directive.graphql
crates/apollo-compiler/tests/extensions.rs
crates/apollo-compiler/tests/main.rs
crates/apollo-compiler/tests/merge_schemas.rs
crates/apollo-compiler/tests/schema.rs

Fixes https://github.com/apollographql/apollo-rs/issues/682

adopt_orphan_extensions opt in flag + allow extending implicit schema

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-parser/CHANGELOG.md

https://github.com/apollographql/apollo-rs/pull/690 reverted hard-to-merge changes, leaving only changelog files to reconcile.

Merge main into compiler-v1.0

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/parser.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/tests/validation/mod.rs

This brings back line/column numbers and serialisability to diagnostics. It essentially fits in the work @goto-bus-stop already did into the new version of the compiler.
The PR includes:
closes #692

feat(compiler): add get_line_column for Diagnostic

---

crates/apollo-compiler/Cargo.toml
crates/apollo-parser/Cargo.toml
crates/apollo-parser/examples/ariadne.rs

Closes https://github.com/apollographql/apollo-rs/pull/602
Some docs still mention miette and link to an example, but they already use a perma-link to an old commit.

Replace miette with ariadne

---

crates/apollo-compiler/src/schema/from_ast.rs

And inline `insert_sticky` to reduce generics saturation, since it only had two callers.

Macroize some redundant code in SchemaBuilder

---

crates/apollo-compiler/src/validation/enum_.rs

Before:
After:
Also removing a temporary string allocation while i'm there

Improve error span for lowercase_enum_value

---

crates/apollo-compiler/src/database/inputs.rs
crates/apollo-compiler/src/database/mod.rs
crates/apollo-compiler/src/database/repr.rs
crates/apollo-compiler/src/database/sources.rs
crates/apollo-compiler/src/executable/validation.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/mod.rs

In the example at https://github.com/apollographql/apollo-rs/pull/676, validation of a trivial (very small) query against a large schema goes from 1.5~2.1 ms to 0.2 ms.

Skip schema AST conversion in ExecutableDocument::validate

---

crates/apollo-compiler/examples/timed.rs

This is a rough port to apollo-compiler 1.0 of the reproduction code provided in https://github.com/apollographql/apollo-rs/issues/442
This is **not** a proper benchmark and I expect we still have low-hanging fruit in terms of improving performance, so don’t look at the numbers too closely.
----
Example run with GitLab’s 34k lines schema:
https://www.apollographql.com/docs/rover/commands/graphs/#graph-introspect
```
rover graph introspect https://gitlab.com/api/graphql > /tmp/gitlab_schema.graphql
```
… and a trivial query:
```
cargo run --release --example timed \
/tmp/gitlab_schema.graphql \
<(echo '{ __typename }')
```
```
Schema parse (1227833 bytes): 63.997 ms
Schema validation: 10.353 ms
Executable document parse (15 bytes): 0.018 ms
Executable document validation: 1.852 ms
```

Add an example measuring parsing time and validation time

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/ast/serialize.rs
crates/apollo-compiler/src/executable/mod.rs
crates/apollo-compiler/src/executable/serialize.rs
crates/apollo-compiler/src/schema/serialize.rs

`Schema`, `ExecutableDocument`, and all AST types already supported serialization to GraphQL syntax through the `Display` trait and the `.serialize()` method. This is now also the case of all other Rust types representing some element of a GraphQL document:
* `schema::Directives`
* `schema::ExtendedType`
* `schema::ScalarType`
* `schema::ObjectType`
* `schema::InterfaceType`
* `schema::EnumType`
* `schema::UnionType`
* `schema::InputObjectType`
* `executable::Operation`
* `executable::Fragment`
* `executable::SelectionSet`
* `executable::Selection`
* `executable::Field`
* `executable::InlineFragment`
* `executable::FragmentSpread`
* `executable::FieldSet`

Add serialization support for everything

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/ast/from_cst.rs
crates/apollo-compiler/src/ast/impls.rs
crates/apollo-compiler/src/ast/mod.rs
crates/apollo-compiler/src/ast/serialize.rs
crates/apollo-compiler/src/executable/mod.rs
crates/apollo-compiler/src/executable/validation.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/parser.rs
crates/apollo-compiler/src/schema/from_ast.rs
crates/apollo-compiler/src/schema/mod.rs
crates/apollo-compiler/src/schema/serialize.rs
crates/apollo-compiler/src/schema/validation.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/validation_db.rs
crates/apollo-compiler/tests/snapshot_tests.rs

Fixes https://github.com/apollographql/apollo-rs/issues/711
The previous names were too similar to `Directive` and `Diagnostic` (singular).

Rename `Directives` and `Diagnostics` to `DirectiveList` and `DiagnosticsList`

---

crates/apollo-compiler/src/validation/fragment.rs
crates/apollo-compiler/test_data/diagnostics/0092_recursive_fragment_spread.graphql
crates/apollo-compiler/test_data/diagnostics/0092_recursive_fragment_spread.txt
crates/apollo-compiler/test_data/serializer/diagnostics/0092_recursive_fragment_spread.graphql

Previously fragment cycle detection only counted fragments that are
directly recursive, where the top-level selection for the fragment
included a fragment spread of itself. But spreading a fragment anywhere
inside a nested field is also problematic and prohibited by spec,
because even if the field you're spreading into is nullable, the client
can't know how deep that recursion goes, and it could be infinite.
Fixes https://github.com/apollographql/apollo-rs/issues/716

Fix validation stack overflow for fragment cycles inside nested fields

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md

[changelog](https://github.com/apollographql/apollo-rs/blob/apollo-compiler%401.0.0-beta.6/crates/apollo-compiler/CHANGELOG.md)
Includes breaking changes but primarily releasing for #733 before we enable rust validation by default in the router
This also requires changes to federation-next and router, I prepped the changes for the router locally.

apollo-compiler@1.0.0-beta.6

---

.circleci/config.yml

Fixes https://github.com/apollographql/apollo-rs/issues/740 somehow 🤷
See https://circleci.com/docs/using-macos/#supported-xcode-versions

Upgrade XCode on CI

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/src/parser/grammar/value.rs
crates/apollo-parser/test_data/parser/ok/0030_values.graphql
crates/apollo-parser/test_data/parser/ok/0030_values.txt

Fixes #744, a critical regression in apollo-parser 0.7.3.

fix(parser): object values can be empty, fixes #744

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md

- **Helper features for `Name` and `Type` - [SimonSapin], [pull/739]:**
* The `name!` macro also accepts an identifier: 
`name!(Query)` and `name!("Query")` create equivalent `Name` values.
* `InvalidNameError` now contain a public `NodeStr` for the input string that is invalid,
and implements `Display`, `Debug`, and `Error` traits.
* Add `TryFrom` conversion to `Name` from `NodeStr`, `&NodeStr`, `&str`, `String`, and `&String`.
* Add a `ty!` macro to build a static `ast::Type` using GraphQL-like syntax.
[SimonSapin]: https://github.com/SimonSapin
[pull/739]: https://github.com/apollographql/apollo-rs/pull/739
- **Add parsing an `ast::Type` from a string - [lrlna] and [goto-bus-stop], [pull/718] fixing [issue/715]**
Parses GraphQL type syntax:
```rust
use apollo_compiler::ast::Type;
let …
```

apollo-compiler@1.0.0-beta.7

---

crates/apollo-compiler/src/validation/selection.rs
crates/apollo-compiler/test_data/ok/0039_field_merging_issue_755.graphql
crates/apollo-compiler/test_data/ok/0039_field_merging_issue_755.txt
crates/apollo-compiler/test_data/serializer/ok/0039_field_merging_issue_755.graphql

In #755, having a top-level selection fragment spread and a fragment spread in a subselection validates the subselection spread against the top-level selection's type instead of the subselection's type. This change fixes the type used for the subselection.
We look up the field definition twice here with `.type_field`, also at the start of the recursion into `same_response_shape()`. I'll see if I can refactor it easily. But not super important compared to the issue it fixes :)

fix(compiler): use correct type for subselections in field merging validation, fixes #755

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-smith/Cargo.toml

- **API refactor to make it harder to ignore errors - [SimonSapin], 
[pull/752] fixing [issue/709]:**
- `ast::Document`, `Schema`, and `ExecutableDocument` not longer contain potential errors
that users need to check separately.
- Instead, various constructors and methods now return a `Result`,
with the `Err` case containing both both errors and a maybe-incomplete value.
- Change `validate` methods of `Schema` and `ExecutableDocument` to take ownership of `self`.
On success they return the schema or document (unmodified) wrapped in a `Valid<_>` marker type,
which is **immutable**.
- Change `ExecutableDocument` to require a `&Valid<Schema>` instead of `&Schema`,
forcing callers to either run validation or opt out explicitly with `Valid::assume_valid`.
- Make `parse_mixed` and `to_mixed` …

apollo-compiler@1.0.0-beta.8

---

crates/apollo-smith/CHANGELOG.md
crates/apollo-smith/Cargo.toml
crates/apollo-smith/README.md

To start using apollo-compiler serialization in apollo-rs and router fuzz tests. Publishing as beta in case we need more breaking changes in apollo-compiler. Removed docs that no longer apply.
(We could also wait with this until compiler is stable? It's just nice to get rid of duplicate deps :) )
---
- **Remove the `parser-impl` feature flag - [SimonSapin], [pull/754].**
This functionality is now always enabled.
- **Use apollo-compiler instead of apollo-encoder for serialization - [SimonSapin], [pull/754].**
The exact string output may change.
- **Make serialization ordering deterministic - [SimonSapin], [pull/754].**
Internally use `IndexMap` and `IndexSet` instead of `IndexMap` and `IndexSet`
[SimonSapin]: https://github.com/SimonSapin
[pull/754]: …

apollo-smith@0.6.0-beta.1

---

CONTRIBUTING.md
xtask/src/main.rs

Runs fmt and clippy with strict settings so when linting passes locally,
it will also pass on CI.

feat(xtask): add xtask lint

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/coordinate.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/schema/mod.rs
crates/apollo-compiler/src/validation/diagnostics.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/src/validation/value.rs
crates/apollo-compiler/test_data/diagnostics/0102_invalid_string_values.txt
crates/apollo-compiler/tests/validation/types.rs
fuzz/Cargo.toml
fuzz/fuzz_targets/coordinate.rs
fuzz/fuzz_targets/strings.rs

Implements parsing and printing for the [Schema Coordinates RFC](https://github.com/graphql/graphql-wg/blob/main/rfcs/SchemaCoordinates.md).
Here, `SchemaCoordinate` is an enum of all the different kinds of coordinates. Each kind of coordinate is also its own type.
```rust
use apollo_compiler::name;
use apollo_compiler::coordinate::{SchemaCoordinate, FieldArgumentCoordinate};
let coord: SchemaCoordinate = "Type.field(argument:)".parse().unwrap();
assert_eq!(coord, SchemaCoordinate::FieldArgument(
FieldArgumentCoordinate {
ty: name!("Type"),
field: name!("field"),
argument: name!("argument"),
},
));
```
```rust
use apollo_compiler::coord;
assert_eq!(coord!(@directive).to_string(), "@directive");
assert_eq!(coord!(@directive(arg:)).to_string(), "@directive(arg:)"); …
```

feat(compiler): add schema coordinates

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/schema/component.rs

Instead of going through `.as_str()`
A Debug impl is already derived including the component information.

feat(compiler): implement fmt::Display for `ComponentName`

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/ast/impls.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/field.rs

Now `argument.is_required() == true` only if the type is non-null and there is no
default value, meaning a value must be provided when it's used. This is how the
[spec](https://spec.graphql.org/draft/#sec-Required-Arguments) describes required arguments.
This seems more useful as the previous implementation can already be achieved
by checking `argument.ty.is_non_null()`.
It's kind of a fix, kind of just a change, kind of breaking...

fix(compiler): InputValueDefinition::is_required() returns false if there is a default value

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/coordinate.rs

All the coordinate types have a `.lookup(&schema)` method.
I omitted the `SchemaLookup` trait that used to be in #757. It was only there to support `schema.lookup(&coord)`, but that's exactly the same as writing `coord.lookup(&schema)`, and it's simpler not to have both.
```rust
assert!(coord!(ObjectDefault.someField(privateArg:)).lookup(&schema).is_ok());
// vs.
assert!(schema.type_field("ObjectDefault", "someField").is_some_and(|f| f.arguments.iter().any(|arg| arg.name == "privateArg")));
```
Type attribute coordinate syntax can refer to object or interface field definitions, input
field definitions, and enum values. `TypeAttributeCoordinate::lookup` returns an enum to
account for those possibilities. To look up a specific kind of type attribute, there are
convenience methods:
- …

feat(compiler): Add `SchemaCoordinate::lookup` methods

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-smith/Cargo.toml

It might be overly dramatic to highlight the `is_required()` as **BREAKING**, but it is technically breaking
---
- **`InputValueDefinition::is_required()` returns false if it has a default value - [goto-bus-stop], [pull/798]**
- Now `argument.is_required() == true` only if the type is non-null and there is no
default value, meaning a value must be provided when it's used.
- **Implement `fmt::Display` for `ComponentName` - [goto-bus-stop], [pull/795]**
- **Add `FieldDefinition::argument_by_name` and `DirectiveDefinition::argument_by_name` - [goto-bus-stop], [pull/801]**
- These methods return an argument definition by name, or `None`.
- **Add `.lookup` methods to schema coordinates - [goto-bus-stop], [pull/803]**
- `coord!(Type).lookup(&schema)` returns the type definition for `Type`.
- …

apollo-compiler@1.0.0-beta.12

---

fuzz/fuzz_targets/coordinate.rs
fuzz/fuzz_targets/lexer.rs
fuzz/fuzz_targets/parser.rs
fuzz/fuzz_targets/strings.rs

Use `RUST_LOG=debug cargo fuzz run $target_name` to get the generated
inputs for fuzzing.

fix(fuzz): enable env_logger in fuzz targets

---

crates/apollo-smith/src/input_value.rs

JSON and GraphQL do not allow Nan or Inf float numbers. 
These are currently being generated by the fuzzer. 
Fixes #812

Fix fuzz f64 generation

---

crates/apollo-smith/src/argument.rs
crates/apollo-smith/src/input_value.rs
crates/apollo-smith/src/variable.rs

As per the spec: https://spec.graphql.org/October2021/#Value Values should not be variables in a const context. 
The TLDR of this is that within schema definitions variables should not be used on arguments. Within operations variables can should be used.
Fixes #810

Add constness to input value generation

---

crates/apollo-compiler/examples/rename.rs
crates/apollo-compiler/src/schema/from_ast.rs

The indexmap crate has deprecated the `::remove` method.
I think `shift_remove()` is the correct one to use in both cases: we
want to maintain order even for orphan type extensions.
Fixes a deprecation warning that is preventing linting from passing on CI.

chore(compiler): explicitly use `IndexMap::{swap,shift}_remove`

---

crates/apollo-parser/src/lexer/lookup.rs
crates/apollo-parser/src/lexer/mod.rs
crates/apollo-parser/src/lexer/token.rs

Basically just bastardizes the good ideas in https://github.com/maciejhirsz/logos in a modest change trying to get the most value without making the code unreadable or hard to maintain. Both functions internally call `is_ascii` to prevent overflows since we're dealing with utf-8.
There's obviously more you could do but from my profiles this seems to be the most impactful paths without making the whole thing unreadable.
Feel free to close as there are obvious tradeoffs here but I opened for your consideration.
The impact of this change really depends on the document being parsed. For small documents its negligible but for large documents, particularly schema SDLs the change speeds things up to ~18%.
```
test result: ok. 0 passed; 0 failed; 65 ignored; 0 measured; 0 filtered out; finished …
```

chore(parser): optimize the most common lexer matches into lookup tables

---

crates/apollo-compiler/src/validation/mod.rs

`debug_assert!` is disabled in release mode, so side effects that we want to preserve should happen outside of it.

Actually run RecursionGuard in release mode

---

crates/apollo-compiler/src/validation/value.rs
crates/apollo-compiler/test_data/ok/0041_unquoted_string_for_custom_scalar.graphql
crates/apollo-compiler/test_data/ok/0041_unquoted_string_for_custom_scalar.txt
crates/apollo-compiler/test_data/serializer/ok/0041_unquoted_string_for_custom_scalar.graphql

Validation does not currently accept something like this:
```graphql
scalar Currency
type Query {
convertToUSD(amount: Int!, currency: Currency!): Int!
}
query {
convertToUSD(amount: 100, currency: EUR)
}
```
which is accepted by graphql-js and (rarely) used by customers. I don't love it, but we already accept enum values nested inside lists or objects as input for custom scalars, so it makes sense to accept this too.
Fixes #834

fix(compiler): accept enum value (unquoted string) as input for custom scalars

---

crates/apollo-compiler/Cargo.toml
crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md

- **optimize the most common lexer matches into lookup tables - [allancalix], [pull/814]**
Parsing large schema documents can be up to 18% faster, typical documents a few percent.
- **fix infinite loops and crashes found through fuzzing - [goto-bus-stop], [pull/828]**
When using a token limit, it was possible to craft a document that would cause an infinite
loop, eventually leading to an out of memory crash. This is addressed along with several panics.
- **reduce intermediate string allocations - [goto-bus-stop], [pull/820]**
[allancalix]: https://github.com/allancalix
[goto-bus-stop]: https://github.com/goto-bus-stop
[pull/814]: https://github.com/apollographql/apollo-rs/pull/814
[pull/820]: https://github.com/apollographql/apollo-rs/pull/820
[pull/828]: …

apollo-parser@0.7.6

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-smith/Cargo.toml

After https://github.com/apollographql/apollo-rs/pull/836
> This release includes a critical fix to overflow protection in validation.
- **New field merging validation implementation - [goto-bus-stop], [pull/816]**
- Uses the much more scalable [XING algorithm].
- This also fixes some invalid selections that were previously accepted by apollo-compiler.
- Selections in fragment definitions are now only validated in the context of the operations they
are used in, reducing duplicate error reports for invalid fragments. This means invalid *unused*
fragments do not produce field merging errors, but they will still raise a different error because
fragments being unused is also an error according to the spec.
- **Add owned IntoIterator for `DirectiveList` types - [SimonSapin], [pull/826]**
- …

apollo-compiler@1.0.0-beta.13

---

crates/apollo-compiler/src/validation/mod.rs

This is not a proper feature! Error codes for validation errors are desired but need careful consideration. This is just a debugging aid so we can get information on validation bugs that were found by folks running the Apollo Router.

Add unstable error name getter to validation errors

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/ast/serialize.rs
crates/apollo-compiler/tests/misc.rs

This helps use indentation in something that is partly but not entirely GraphQL syntax, such as the debugging representation of an Apollo Router query plan. Example: `document.serialize().initial_indent_level(2).to_string()`

feat(compiler): serialize with initial indentation

---

crates/apollo-compiler/tests/executable.rs
crates/apollo-parser/src/parser/grammar/field.rs
crates/apollo-parser/test_data/parser/err/0045_ignored_token_spans.graphql
crates/apollo-parser/test_data/parser/err/0045_ignored_token_spans.txt
crates/apollo-parser/test_data/parser/err/0055_object_definition_with_missing_name.graphql
crates/apollo-parser/test_data/parser/err/0055_object_definition_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0056_object_definition_with_missing_curly.graphql
crates/apollo-parser/test_data/parser/err/0056_object_definition_with_missing_curly.txt
crates/apollo-parser/test_data/parser/err/0057_object_definition_with_missing_fields.graphql
crates/apollo-parser/test_data/parser/err/0057_object_definition_with_missing_fields.txt
crates/apollo-parser/test_data/parser/err/0058_interface_definition_with_missing_name.graphql
crates/apollo-parser/test_data/parser/err/0058_interface_definition_with_missing_name.txt
crates/apollo-parser/test_data/parser/err/0059_interface_definition_with_missing_fields.graphql
crates/apollo-parser/test_data/parser/err/0059_interface_definition_with_missing_fields.txt
crates/apollo-parser/test_data/parser/err/0060_interface_definition_with_missing_curly.graphql
crates/apollo-parser/test_data/parser/err/0060_interface_definition_with_missing_curly.txt

The parser is a bit lenient around letting types being defined without fields.
The example below should fail parsing but doesn't today:
```
type User {
}
```
This PR implements the missing validation to bail parsing for object types and interfaces when defined as empty (within curly braces).
The parser already implemented this validation for enum and input types.

Bug fix - implement missing parser validation for interface and object having missing fields

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-smith/Cargo.toml

For after https://github.com/apollographql/apollo-rs/pull/849
- **Serialize with initial indentation - [SimonSapin], [pull/848]**
This helps use indentation in something that is partly but not entirely GraphQL syntax,
such as the debugging representation of an Apollo Router query plan.
Example: `document.serialize().initial_indent_level(2).to_string()`
- **Add validation requiring composite types declare fields - [tinnou], [pull/847]**
Object types, interfaces, enums, unions, and input objects must all have at least one
member. This is now checked in schema validation.
[SimonSapin]: https://github.com/SimonSapin
[tinnou]: https://github.com/tinnou
[pull/847]: https://github.com/apollographql/apollo-rs/pull/847
[pull/848]: https://github.com/apollographql/apollo-rs/pull/848

apollo-compiler@1.0.0-beta.15

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/executable/from_ast.rs
crates/apollo-compiler/src/executable/mod.rs
crates/apollo-compiler/src/validation/diagnostics.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/value.rs
crates/apollo-compiler/src/validation/variable.rs

With some additions to the error structures to pass through the data required.
This PR adds a `.unstable_to_json_compat()` function to diagnostics that returns best-effort error messages in the graphql-js format. Some things like "Did you mean?" are omitted intentionally. There are minor differences in a handful of other messages, but much fewer than before, and hopefully it'll be obvious to users that the meaning is the same. One example difference is the `UnsupportedValueType` message, which in graphql-js is a customisable type-specific validation, but in apollo-rs is a fixed check based only on what the spec knows about builtin scalars, so the error is a bit less specific.
The new API is only meant for use in the Apollo Router, temporarily, exempt from semver, and any other users will …

Add a graphql-js compatible-ish error serialization for Apollo Router

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-smith/Cargo.toml

> This release has no user-facing changes.
- **Add GraphQL validation compatibility API for Apollo Router - [goto-bus-stop] in [pull/853]**
Enables large-scale production deployment of apollo-compiler's validation implementation.
[goto-bus-stop]: https://github.com/goto-bus-stop
[pull/853]: https://github.com/apollographql/apollo-rs/pull/853

apollo-compiler@1.0.0-beta.16

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/src/diagnostic.rs
crates/apollo-compiler/src/parser.rs
crates/apollo-compiler/tests/validation/mod.rs

ariadne 0.4.1 supports using byte indices directly. This patch removes `MappedSource`, saving some computation but mostly memory usage when generating JSON or CLI reports for diagnostics.
We could also use `NodeLocation` as an ariadne span directly by implementing the `Span` trait for it. It's a little more convenient when creating the reports. I opted not to do that because it's user-visible if users install ariadne manually, instead I kept the internal conversion to a `(FileId, Range<u64>)` span.

Remove ariadne byte/char mapping

---

crates/apollo-compiler/examples/introspect.rs

Wanted to try out some queries so I wrote this :smile_cat:

chore(compiler): add a runnable example for experimental introspection implementation

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/benches/fragments_validation.rs
crates/apollo-compiler/src/executable/validation.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/src/validation/fragment.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/selection.rs

Fixes #862.
I had proposed a different approach that would let us cache the implementers map for as long as the schema is immutable, so it could be reused for different query validations. That approach had an issue that made `Valid::assume_valid_ref` very, very subtle to use, so we are not doing that right now.
This is a less ideal version but it does solve the immediate problem. We had an `OperationValidationConfig` structure that contains contextual information about the current operation. This extends that idea to have an `ExecutableValidationContext` for the whole document, and "child" `OperationValidationContext`s for each operation.
The included benchmark goes from 200ms of validation time to 2ms.

fix(compiler): cache the implementers map per executable document

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-smith/Cargo.toml

- **Fix validation performance bug - [goto-bus-stop] in [issue/862], [pull/863]**
Adds a cache in fragment spread validation, fixing a situation where validating a query
with many fragment spreads against a schema with many interfaces could take multiple
seconds to validate.
- **Remove ariadne byte/char mapping - [goto-bus-stop] in [pull/855]**
Generating JSON or CLI reports for apollo-compiler diagnostics used a translation layer
between byte offsets and character offsets, which cost some computation and memory
proportional to the size of the source text. The latest version of [ariadne] allows us to
remove this translation.
[goto-bus-stop]: https://github.com/goto-bus-stop
[issue/862]: https://github.com/apollographql/apollo-rs/issues/862
[pull/855]: …

apollo-compiler@1.0.0-beta.17

---

crates/apollo-smith/Cargo.toml
crates/apollo-smith/examples/generate.rs
crates/apollo-smith/examples/schema.graphql
crates/apollo-smith/src/selection_set.rs
crates/apollo-smith/src/snapshot_tests.rs

This changes the field generation algorithm in apollo-smith to allow more variety, because the previous implementation was too biased towards the first field specified in a type.
This also adds an example to generate a random query from a schema.
One thing that comes out of these tests is that we need the input data for Arbitrary to be large enough, otherwise once it has no more bytes to consume, it returns 0 every time and the selections get no more variations

apollo-smith: more varied fields generation

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/node.rs

Hashing is much less important to apollo-compiler as it was when we were using Salsa. Many of the structs stored in `Node<_>` don’t even implement `Hash` since they contain `IndexMap` which doesn’t.
We lose: potential CPU time if repeatedly hashing nodes. `ast::Definition` implements `PartialEq` and `Hash` by traversing the whole subtree, which can be expensive. We gain: 8 fewer bytes in the heap allocation of every `Node`, and slightly less code complexity.

Remove `Hash` cache in `Node<T>`

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-smith/Cargo.toml

- **`Name` representation change - [SimonSapin] in [pull/868].** The memory representation of GraphQL names is changed to use `Arc<str>` or `&'static str` internally, and provide corresponding cheap conversions. This may also help enable [string interning] in a future compiler version.
* `Name` should now be imported from the crate root. The previous paths (`apollo_compiler::ast::Name`, `apollo_compiler::executable::Name`, and `apollo_compiler::schema::Name`) now emit a deprecation warning and will be removed in a later version.
* `NodeStr` has been removed, with its functionality folded into `Name`
* `ast::Value::String` now contains a plain `String` instead of `NodeStr`. `Value` itself is in a `Node<_>` that contains the same source span as `NodeStr` did.
* Descriptions are now …

Prepare apollo-compiler@1.0.0-beta.18 release

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/src/executable/validation.rs
crates/apollo-compiler/src/validation/selection.rs

In #816, to avoid cloning a big `Vec` for use as a hash key, I instead used the hash of the Vec as a key. I guess it's possible to get a hash collision that way and produce the wrong result.
Here I avoid the clone by allocating field selections into an arena allocator. The allocator outlives `FieldsInSetCanMerge` so we can pass around references to slices, and we can store the reference in the key and the value at the same time.
We already didn't deallocate the `Vec`s until the `FieldsInSetCanMerge` struct is dropped so the memory usage is the same.

fix(compiler): remove potential hash collision bug from `FieldsInSetCanMerge`

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/src/collections.rs
crates/apollo-compiler/src/executable/from_ast.rs
crates/apollo-compiler/src/executable/mod.rs
crates/apollo-compiler/src/execution/engine.rs
crates/apollo-compiler/src/execution/introspection_split.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/parser.rs
crates/apollo-compiler/src/schema/from_ast.rs
crates/apollo-compiler/src/schema/mod.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/selection.rs
crates/apollo-compiler/tests/merge_schemas.rs
crates/apollo-compiler/tests/snapshot_tests.rs

This changeset introduces ahash, a hasher that is faster than the one provided by the stdlib.
It exposes a collections::fast module, that can be used by other libraries that rely on apollo-rs types. This makes it easier for the apollo-rs to swap implementations in the future if needs be.

Introduce a faster hasher

---

crates/apollo-compiler/src/validation/value.rs
crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/test_data/diagnostics/0007_operation_with_undefined_variables.graphql
crates/apollo-compiler/test_data/diagnostics/0007_operation_with_undefined_variables.txt
crates/apollo-compiler/test_data/diagnostics/0101_mismatched_variable_usage.graphql
crates/apollo-compiler/test_data/diagnostics/0101_mismatched_variable_usage.txt
crates/apollo-compiler/test_data/diagnostics/0111_const_value.graphql
crates/apollo-compiler/test_data/diagnostics/0111_const_value.txt
crates/apollo-compiler/test_data/serializer/diagnostics/0007_operation_with_undefined_variables.graphql
crates/apollo-compiler/test_data/serializer/diagnostics/0101_mismatched_variable_usage.graphql
crates/apollo-compiler/test_data/serializer/diagnostics/0111_const_value.graphql

Previously, an operation like this would pass validation:
```graphql
query {
field(listArg: [$undefinedVar])
}
```
It turns out this is not very common as we haven't seen this cause a problem
on hundreds of thousands of operations. But it does happen :)
This moves the UndefinedVariable rule to value validation: we are already
recursing into the value here, and we're actually also already checking
that the variable exists, so this is a simpler place to do it than in
the `variable.rs` module.
This fixes the immediate problem. There are two things that I may be able to
address here before we merge it time willing...

fix(compiler): fix validation for undefined variables nested in values

---

crates/apollo-compiler/src/validation/variable.rs

A small thing I was doing for #883 but we merged that early ;)
The validation used a hash map and two hash sets. We can do the exact same validation with only a hash map, by first putting all declared variables in the hash map, and removing variables as we see them used. Then at the end we only have unused variables in the map.

chore(compiler): make unused variable validation more efficient

---

crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/test_data/diagnostics/0009_operation_with_undefined_variables_in_fragment.graphql
crates/apollo-compiler/test_data/diagnostics/0009_operation_with_undefined_variables_in_fragment.txt
crates/apollo-compiler/test_data/ok/0042_used_variable_in_operation_directive.graphql
crates/apollo-compiler/test_data/ok/0042_used_variable_in_operation_directive.txt
crates/apollo-compiler/test_data/ok/0115_interface_definition_with_extension_defines_field.txt
crates/apollo-compiler/test_data/serializer/diagnostics/0009_operation_with_undefined_variables_in_fragment.graphql
crates/apollo-compiler/test_data/serializer/ok/0042_used_variable_in_operation_directive.graphql

Fixes apollo-compiler rejecting valid queries, where a variable is used inside a directive applied directly to an operation. This is indeed allowed by spec.
Extended existing tests to check directives on fragment definitions as well, because I also found it a little surprising that they allow variables too.

fix(compiler): identify variables in operation directives

---

crates/apollo-parser/src/error.rs
crates/apollo-parser/src/lexer/mod.rs
crates/apollo-parser/test_data/lexer/err/0014_plus_sign.txt
crates/apollo-parser/test_data/lexer/err/0015_minus_sign.txt
crates/apollo-parser/test_data/lexer/err/0016_leading_zero.txt
crates/apollo-parser/test_data/lexer/err/0017_number_lookahead.txt
crates/apollo-parser/test_data/lexer/err/0029_not_whitespace.txt

Fixes https://github.com/apollographql/apollo-rs/issues/731
I _think_ these are all the missing locations, but there are a few more places that do `Error::new` - as far as I can tell though these errors are getting location information filled in at a later stage (via `self.done()`).
I saw the original issue proposed removing `Error::new` completely - I'm happy to do it, but it would be a break, and I'm not sure what the policy on those is in this repo.

fix(parser): add missing location information for some lexer errors

---

crates/apollo-compiler/src/validation/fragment.rs
crates/apollo-compiler/test_data/diagnostics/0091_recursive_interface_definition.graphql
crates/apollo-compiler/test_data/diagnostics/0091_recursive_interface_definition.txt
crates/apollo-compiler/test_data/ok/0116_interface_without_implementations.graphql
crates/apollo-compiler/test_data/ok/0116_interface_without_implementations.txt
crates/apollo-compiler/test_data/serializer/diagnostics/0091_recursive_interface_definition.graphql
crates/apollo-compiler/test_data/serializer/ok/0116_interface_without_implementations.graphql

This `Intf` has no implementations. As written in the spec, doing a `... on Intf` fragment spread should never work, as the set of possible types is empty and can never intersect with the parent type. However, implementations like graphql-js and graphql-go have an early check, accepting the fragment if the type condition is equal to the parent type. This tests reproduces that.
We may want to align with graphql-js and graphql-go rather than the spec here for compatibility? Though it's not something that's likely to happen in the real world.
Ref https://github.com/graphql/graphql-spec/issues/1109

fix(compiler): fix validation for fragment spread of interface without implementers

---

crates/apollo-compiler/src/built_in_types.graphql
crates/apollo-compiler/src/execution/introspection_execute.rs
crates/apollo-compiler/src/execution/introspection_split.rs
crates/apollo-compiler/src/execution/resolver.rs
crates/apollo-compiler/src/execution/response.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/test_data/diagnostics/0050_directives_in_invalid_locations.txt
crates/apollo-compiler/test_data/diagnostics/0054_argument_not_provided.txt
crates/apollo-compiler/test_data/diagnostics/0087_fragment_type_condition_on_composite_types.txt
crates/apollo-compiler/test_data/diagnostics/0102_invalid_string_values.txt
crates/apollo-compiler/test_data/introspection/response_full.json
crates/apollo-compiler/test_data/ok/0012_introspection_query.txt
crates/apollo-compiler/test_data/ok/0026_type_introspection.txt
crates/apollo-compiler/tests/validation/types.rs

We fuzz many introspection queries then expect apollo-compiler and graphql-js to return equivalent responses. Some of these changes help writing the fuzz targets, others fix bugs found by fuzzing.

Fixes and additions to schema introspection, for comparative fuzzing

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/execution/introspection_execute.rs
crates/apollo-compiler/src/execution/introspection_max_depth.rs
crates/apollo-compiler/src/execution/introspection_split.rs
crates/apollo-compiler/src/execution/mod.rs
crates/apollo-compiler/tests/introspection_max_depth.rs
crates/apollo-compiler/tests/main.rs

* https://github.com/graphql/graphql-js/blob/v17.0.0-alpha.7/src/validation/rules/MaxIntrospectionDepthRule.ts
* https://github.com/graphql/graphql-js/blob/v17.0.0-alpha.7/src/validation/__tests__/MaxIntrospectionDepthRule-test.ts
Without this rule, a malicious client could cause huge introspection responses that grow exponentially with the list nesting level in the query.
Instead of a validation rule, this check is performed as part of `SchemaIntrospectionSplit::split`. graphql-js allows users to disable or enable specific validation rules, with max introspection depth being part of "recommended" rules. apollo-compiler does not have this mechanism, so `document.validate()` always performs validation as per the GraphQL spec.
The depth limit is hard-coded to 3, and applied to specific …

Port MaxIntrospectionDepthRule from graphql-js

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/executable/mod.rs
crates/apollo-compiler/tests/executable.rs

* `OperationMap::len` and `OperationMap::is_empty`, making it more like a collection type
* `Operation::all_fields` and `Operation::root_fields` iterators

Add convenience APIs on operations

---

crates/apollo-compiler/src/schema/from_ast.rs
crates/apollo-compiler/tests/extensions.rs

Building a schema with the `adopt_orphan_extensions` option enabled yields an error in the following simple case:
```graphql
extend schema { query: Query }
type Query { x: Int }
```
```
Error: duplicate definitions for the `query` root operation type
╭─[schema.graphql:2:25]
│
2 │         extend schema { query: Query }
│                         ──────┬─────  
│                               ╰─────── `query` redefined here
───╯
```
Currently, it accidentally makes the assumption that a schema extension's root operations do not use a default name, which explains why [this test](https://github.com/apollographql/apollo-rs/blob/caf820d86a03db3650149cefe6157442c73d7e50/crates/apollo-compiler/tests/extensions.rs#L5-L10) currently passes but the failing test from …

fix: `adopt_orphan_extensions` + schema extensions + implicit root operation interaction

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-compiler/src/schema/from_ast.rs
crates/apollo-compiler/tests/extensions.rs
crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md
crates/apollo-smith/CHANGELOG.md
crates/apollo-smith/Cargo.toml
crates/apollo-smith/README.md

`adopt_orphan_extensions` is a non-standard mode so we don’t have a spec to precisely define its behavior, but I think this behavior is more consistent. See new test for an example.
Also prepare releases for:
* apollo-parser@0.8.2
* apollo-compiler@1.0.0-beta.22
* apollo-smitch@0.12.0 (only needed to update the pinned compiler dependency)

An adopted schema extension disables implicit root operations + Prep releases

---

crates/apollo-compiler/src/parser.rs
crates/apollo-compiler/tests/introspection_max_depth.rs
crates/apollo-compiler/tests/introspection_split.rs

This felt nicer in a case like the below:
https://github.com/apollographql/router/blob/e9dc61255e87294f624a0ecc68ac7c83fab5a7f0/apollo-federation/src/sources/connect/validation/snapshots/validation_tests%40rest.graphql.snap#L10-L25
It's not a big deal though. If anyone isn't that enthusiastic about it
we can just not :)

feat(compiler): add compact Debug impl for LineColumn

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/benches/directives_validation.rs

It could be risky if these are slow to parse or validate, as it's easy
to produce a malicious document with many directives.
Parsing + validation of a document with 10K directives seems to take
about 3 ms on my laptop, which seems acceptable.
```
many_same_directive     time:   [3.0178 ms 3.0297 ms 3.0423 ms]
change: [-0.4138% +0.3025% +0.9324%] (p = 0.41 > 0.05)
No change in performance detected.
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
many_same_directive_query
time:   [3.0302 ms 3.0358 ms 3.0419 ms]
change: [-0.7244% -0.4807% -0.2229%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
3 (3.00%) high mild
1 (1.00%) high severe
many_invalid_directive  time:   [2.8780 ms 2.8877 ms 2.8980 ms]
change: [-0.7915% …
```

chore(compiler): add some benchmarks with many duplicate directives

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/value.rs
crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/test_data/diagnostics/0102_invalid_string_values.graphql
crates/apollo-compiler/test_data/diagnostics/0102_invalid_string_values.txt
crates/apollo-compiler/test_data/diagnostics/0111_const_value.txt
crates/apollo-compiler/test_data/serializer/diagnostics/0102_invalid_string_values.graphql
crates/apollo-compiler/tests/validation/variable.rs

Fixes https://github.com/apollographql/apollo-rs/issues/852
GraphQL values can be of different kinds, including variables with the `$x` syntax. Variables are not allowed in some contexts, such as schemas. The parser already rejects them as syntax errors, but the Rust API allows mutating a document and representing variable values in contexts where they are not allowed.
It was already the case that would usually cause a validation error like ``variable `$x` is not defined``. This PR ensures and tests that this is the case for every relevant context. It also makes related drive-by fixes:
* Validate the default value of input fields and arguments
* Validate the default value of variables once at their definition, not at every usage of the variable. This fixes duplicate diagnostics for a …

Make variables in const contexts validation errors

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/tests/validation/variable.rs

This turns out to break enough existing schemas (Router rejects them as invalid where it previously accepted them) that we consider it a breaking change.
See https://github.com/apollographql/apollo-rs/issues/928

Revert default value validation of input fields and arguments

---

crates/apollo-compiler/examples/extract_directives_used_by_query.rs

Update the apollo-compiler directive extraction example to handle fragments in queries. Please give this a look in case I've bungled it :) Closes https://github.com/apollographql/apollo-rs/issues/935

chore(compiler): update directive extract example to handle fragments

---

.circleci/config.yml

[SECOPS-4142](https://apollographql.atlassian.net/browse/SECOPS-4142)
Removes the security scans running on this repo in CircleCI in favor of our Github App-based implementation of the same scans. After this PR merges, I'll update the branch protection rules on the repo to require the Github App-based jobs.
The Github app implementation improves both the time it takes to run these tests and better supports pull requests from forks.
- Removed the `gitleaks` and `semgrep` jobs that were running in CircleCI. 
[SECOPS-4142]: https://apollographql.atlassian.net/browse/SECOPS-4142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

remove CCI-based security scans

---

.circleci/config.yml
crates/apollo-compiler/Cargo.toml
crates/apollo-parser/Cargo.toml

This essentially reverts #933.
Apollo Router is no longer stuck on rustc 1.76.0, so we don't have a reason to stay on that old version.
We could consider using the same rustc version as Router (so 1.83.0 at the time of writing), in case some other constraint forces us to pin it again. I think it's much less likely now without Deno, and it's more work to update both repositories if we are pinning a version in both, so I am not doing it here.

chore: remove rust 1.76.0 MSRV, and unpin rowan

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md

The rowan update was not on crates.io yet

Prepare apollo-parser@0.8.4

---

crates/apollo-compiler/src/parser.rs

We end up needing this for composition validations around connectors so we can store locations for attribution and look up line/col only when required.

Provide access to line/col lookup on a `SourceFile`

---

.circleci/config.yml
Cargo.toml
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/src/executable/mod.rs
crates/apollo-compiler/src/validation/mod.rs
examples/validation-wasm-demo/Cargo.toml
examples/validation-wasm-demo/README.md
examples/validation-wasm-demo/index.html
examples/validation-wasm-demo/src/lib.rs

This replace compiling the library with wasm target on CI, which recently started failing with:
```
error: the wasm*-unknown-unknown targets are not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
--> /home/circleci/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.15/src/lib.rs:342:9
|
342 | /         compile_error!("the wasm*-unknown-unknown targets are not supported by \
343 | |                         default, you may need to enable the \"js\" feature. \
344 | |                         For more information see: \
345 | |                         https://docs.rs/getrandom/#webassembly-support");
| |________________________________________________________________________^ …
```

Add WebAssembly demo

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/src/executable/mod.rs
crates/apollo-compiler/src/executable/validation.rs
crates/apollo-compiler/src/introspection/max_depth.rs
crates/apollo-compiler/src/introspection/mod.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/src/validation/fragment.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/selection.rs
crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/tests/executable.rs
crates/apollo-compiler/tests/validation/recursion.rs

Due to named fragments being processed more than once, some error messages were getting duplicated. This PR fixes the relevant functions, and also avoids reprocessing named fragments in other parts of the codebase.

Avoid reprocessing named fragments

---

crates/apollo-compiler/Cargo.toml
crates/apollo-parser/Cargo.toml

After #960, apollo-rs does not work with ariadne 0.5.0, so we should bump the
minimum version to 0.5.1.

deps: increase minimum ariadne version

---

crates/apollo-compiler/src/executable/validation.rs
crates/apollo-compiler/src/validation/fragment.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/src/validation/operation.rs
crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/tests/validation/recursion.rs

This adds stack overflow protection to the existing "Variable Is Used" and "Fragment Is Used" validations, and the newly introduced subscription validation #963. Additionally, this significantly improves performance of the "Fragment Is Used" validation, which used to walk almost the entire document AST for each fragment definition, and now only does it once.
You need *a lot* of fragments to cause these to overflow, so it's only a problem for users who don't have a token limit configured or have it set much higher than the Router default.

Harden stack overflow protection

---

crates/apollo-compiler/src/ast/impls.rs
crates/apollo-compiler/src/node.rs

Implements mutable versions of some functions used to access directives and their arguments. This improves the ergonomics for some of the composition work we're doing in https://github.com/apollographql/router/pull/7235.

Simplify directive mutation

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md

- **Reject `@skip`/`@include` on subscription root fields - [DerekKuc] [SimonSapin] and [goto-bus-stop], [pull/963]**
This implements a [GraphQL spec RFC](https://github.com/graphql/graphql-spec/pull/860), rejecting
subscriptions in validation that can be invalid during execution.
- **New shorthand methods for mutable directive argument access - [tninesling], [pull/967]**
Introduces new methods:
- `DirectiveList::get_all_mut`
- `DirectiveList::argument_by_name_mut`
- `DirectiveList::specified_argument_by_name_mut`
- **Update `ariadne` trait implementations - [lrlna], [pull/960]**
`ariadne@0.5.1` release changed their type signature for `ariadne::Cache` trait, which required an
update to `apollo-compiler`'s implementation of `ariadne::Cache<FileId>`. 
This release also had a slight change …

apollo-compiler@1.28.0

---

.github/renovate.json5

Pinning our dependencies to a specific version would cause a world of pain any time any Router dependency updates, and increase the maintenance burden of apollo-rs. Let's not do that.
Ref https://github.com/apollographql/apollo-rs/pull/969

chore: make renovate not pin deps

---

.cargo/config.toml
examples/validation-wasm-demo/Cargo.toml

A transitive dependency updated `getrandom` to v0.3, which requires more configuration.

Fix WASM compile test on CI

---

crates/apollo-compiler/src/schema/mod.rs

I overlooked this in 1.29.0 release.

fix(compiler): make `iter_origins` methods public

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/schema/from_ast.rs
crates/apollo-compiler/tests/validation/types.rs

Adds new `ignore_builtin_redefinitions` option on the `SchemaBuilder` to allow SDL to contain built-in scalar re-definitions. Re-definitions are going to be effectively ignored and compiler will continue to use built-in GraphQL spec definitions. While [GraphQL spec](https://spec.graphql.org/October2021/#sec-Scalars) explicitly specifies following
```
When representing a GraphQL schema using the type system definition language, all built-in scalars must be omitted for brevity.
```
`graphql-js` reference implementation does not enforce this and does not report any errors even if built-in scalars are present in SDL. This change allows users to skip this validation to match `graphql-js` behavior.

feat(compiler): allow SDL to contain built-in scalar definitions
