crates/apollo-parser/src/lexer/mod.rs
crates/apollo-parser/src/parser/grammar/extensions.rs
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzz_target_1.rs
fuzz/fuzz_targets/lexer.rs
fuzz/fuzz_targets/parser.rs

following up on https://github.com/apollographql/apollo-rs/pull/115#discussion_r759136264, I set up a fuzzing test (I see @garypen worked on it too in https://github.com/apollographql/apollo-rs/issues/59#issuecomment-960620361 ) and it is already triggering issues in the lexer, that should be easy to address

set up fuzzing for apollo-parser

---

crates/apollo-parser/test_data/parser/ok/0006_selection_with_fragment_spread.graphql
crates/apollo-parser/test_data/parser/ok/0006_selection_with_fragment_spread.txt

follow up to 164 with a few extra test cases in our testing suite.

chore(apollo-parser): extra fragments in operation definition test cases

---

crates/apollo-encoder/CHANGELOG.md

Prep for a new apollo-encoder release: adding a CHANGELOG template.

chore(apollo-encoder): create CHANGELOG.md

---

.circleci/config.yml

chore(circle-ci): update github orb

---

crates/apollo-parser/src/parser/grammar/directive.rs

apollo-parser: directive locations are now parsed correctly with a leading |

---

crates/apollo-smith/src/field.rs
crates/apollo-smith/src/fragment.rs
crates/apollo-smith/src/interface.rs
crates/apollo-smith/src/lib.rs
crates/apollo-smith/src/object.rs
crates/apollo-smith/src/selection_set.rs

Added support of interface definition in the stack to fill an operation with correct fields.

feat(apollo-smith): add interface definition to internal stack

---

crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/lib.rs
crates/apollo-compiler/src/validation/interfaces.rs
crates/apollo-compiler/src/validation/objects.rs
crates/apollo-compiler/src/validation/operations.rs
crates/apollo-compiler/src/validation/unions.rs
crates/apollo-compiler/test_data/diagnostics/0036_object_type_with_non_output_field_types.txt
crates/apollo-compiler/test_data/diagnostics/0037_interface_with_non_output_fields.txt
crates/apollo-compiler/test_data/diagnostics/0042_mutation_operation_with_undefined_fields.txt
crates/apollo-compiler/test_data/diagnostics/0043_undefined_union_member.graphql
crates/apollo-compiler/test_data/diagnostics/0043_undefined_union_member.txt
crates/apollo-compiler/test_data/diagnostics/0044_union_member_not_of_object_type.graphql
crates/apollo-compiler/test_data/diagnostics/0044_union_member_not_of_object_type.txt

- validates that union members are defined in scope
- validates that union members are of object type

feat(apollo-compiler): additional union validations

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-compiler/src/lib.rs

Initial publish of `apollo-compiler` crate.

apollo-compiler@0.1.0

---

crates/apollo-compiler/Cargo.toml

For context see https://github.com/apollographql/apollo-rs/issues/288

Support wasm compile target in apollo-compiler

---

crates/apollo-compiler/src/queries/values.rs

Exposes the description fields

feat(apollo-compiler): Add description getters

---

crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/test_data/diagnostics/0045_operation_with_unused_variable_in_fragment.graphql
crates/apollo-compiler/test_data/diagnostics/0045_operation_with_unused_variable_in_fragment.txt
crates/apollo-compiler/test_data/ok/0013_operation_with_used_variable_in_fragment.graphql
crates/apollo-compiler/test_data/ok/0013_operation_with_used_variable_in_fragment.txt

fix(compiler): unused variables return an error diagnostic

---

crates/apollo-compiler/Cargo.toml
crates/apollo-encoder/Cargo.toml
crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md
crates/apollo-smith/Cargo.toml

This fails for a little bit until we publish 0.3.0 of apollo-parser

apollo-parser@0.3.0

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/src/ast/node_ext.rs

See respective commit messages

Extend ast::*Value node conversions

---

crates/apollo-smith/CHANGELOG.md
crates/apollo-smith/Cargo.toml
crates/apollo-smith/README.md

[Rendered changelog](https://github.com/apollographql/apollo-rs/blob/apollo-smith@0.2.0/crates/apollo-smith/CHANGELOG.md#020---2022-11-08)
closes #351

apollo-smith@0.2.0

---

crates/apollo-compiler/src/database/document.rs

This allows to find any definitions that use a particular directive in its definition. This won't look for any field or argument level directives used as it would make for a very ambiguous return type, but instead on any definition level directive usages in the following [directive locations](https://spec.graphql.org/October2021/#TypeSystemDirectiveLocation): schema, scalar, object, interface, union, enum, input object.

feat(compiler): find any definitions with a specified directive

---

crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/validation/validation_db.rs

Add extension definitions to the HIR and subtype queries

---

crates/apollo-compiler/Cargo.toml
crates/apollo-encoder/Cargo.toml
crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md
crates/apollo-smith/Cargo.toml

[Changelog](https://github.com/apollographql/apollo-rs/blob/apollo-parser@0.4.0/crates/apollo-parser/CHANGELOG.md)

apollo-parser@0.4.0

---

crates/apollo-encoder/CHANGELOG.md
crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/README.md
crates/apollo-parser/Cargo.toml
crates/apollo-smith/Cargo.toml

[Changelog](https://github.com/apollographql/apollo-rs/blob/apollo-encoder@0.4.0/crates/apollo-encoder/CHANGELOG.md)

apollo-encoder@0.4.0

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md

[Changelog](https://github.com/apollographql/apollo-rs/blob/apollo-compiler%400.4.0/crates/apollo-compiler/CHANGELOG.md)

apollo-compiler@0.4.0

---

crates/apollo-smith/CHANGELOG.md
crates/apollo-smith/Cargo.toml
crates/apollo-smith/README.md

i published smith@0.3.0 before encoder@0.4.0, so now this needs to be republished 🤪 
already yanked 0.3.0.

apollo-smith@0.3.1

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml

[Changelog](https://github.com/apollographql/apollo-rs/blob/apollo-parser@0.4.1/crates/apollo-parser/CHANGELOG.md)

apollo-parser@0.4.1

---

crates/apollo-compiler/examples/extend_db.rs
crates/apollo-compiler/src/database/document.rs
crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/database/hir_db.rs
crates/apollo-compiler/src/validation/validation_db.rs

This struct contains one field per kind of definition. Where a name is mandatory, that field is a map keyed by name.
The `type_system_definitions` query now returns this struct instead of `Vec<Definition>`.
The `db_definitions` query has been removed. Instead its callers should use some combination of `type_system_definitions`, `all_operations`, and/or `all_fragments`.
`find_definition_by_name` and `find_type_system_definition_by_name` have also been removed. Instead its callers should used other `*_by_name` queries for more specific kinds of definitions.

Replace `hir::Definition` enum with `TypeSystemDefinitions` struct

---

crates/apollo-compiler/examples/documents/get_dog_name.graphql
crates/apollo-compiler/examples/documents/get_dog_with_fragments.graphql
crates/apollo-compiler/examples/documents/schema.graphql
crates/apollo-compiler/examples/documents/schema_extension.graphql
crates/apollo-compiler/examples/multi_source_validation.rs

todo: example of watching a dir for changes and updating the compiler accordingly. 
anything else that would be helpful for people to see with this new change?

docs(compiler): create compiler from multiple sources

---

crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/benches/multi_source.rs
crates/apollo-compiler/benches/testdata/simple_schema.graphql
crates/apollo-compiler/benches/testdata/supergraph.graphql
crates/apollo-compiler/benches/testdata/supergraph_query.graphql

Lots of room for improvement 🎉 Good to have this straight up in the crate.
```shell
supergraph_compiler     time:   [753.81 us 755.47 us 757.09 us]                                
change: [-3.3862% -1.8438% -0.6501%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 2 outliers among 100 measurements (2.00%)
2 (2.00%) high severe
supergraph_compiler_with_validation                                                                            
time:   [421.27 us 425.18 us 430.81 us]
change: [-1.0073% -0.4215% +0.3017%] (p = 0.19 > 0.05)
No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
5 (5.00%) high mild
2 (2.00%) high severe
simple_query_compiler   time:   [19.243 us 19.308 us 19.387 us]                                   
change: [-0.3771% +0.0987% …
```

chore(compiler): add benchmarks

---

crates/apollo-smith/src/enum_.rs

it was not compiling with these features enabled

fix TryFrom impl to use the std Result

---

crates/apollo-compiler/src/validation/validation_db.rs

oooops! #417 broke main a tiny bit

fix(compiler): don't deref op.operation_ty()

---

crates/apollo-compiler/Cargo.toml
crates/apollo-encoder/Cargo.toml
crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-smith/Cargo.toml

[Rendered](https://github.com/apollographql/apollo-rs/blob/apollo-parser@0.5.0/crates/apollo-parser/CHANGELOG.md)

apollo-parser@0.5.0

---

crates/apollo-encoder/CHANGELOG.md
crates/apollo-encoder/Cargo.toml
crates/apollo-parser/Cargo.toml
crates/apollo-smith/Cargo.toml

[Rendered](https://github.com/apollographql/apollo-rs/blob/apollo-encoder@0.5.0/crates/apollo-encoder/CHANGELOG.md)

apollo-encoder@0.5.0

---

xtask/Cargo.toml
xtask/src/codegen/mod.rs
xtask/src/main.rs

Started doing this for #471 but then decided to go a different route with that PR. I already did the work so we can merge this separately 🤷🏻‍♀️

chore(xtask): update xtask dependencies

---

crates/apollo-compiler/CHANGELOG.md

Fixes https://github.com/apollographql/apollo-rs/issues/468, together with https://github.com/apollographql/apollo-rs/pull/481, https://github.com/apollographql/apollo-rs/pull/482, and https://github.com/apollographql/apollo-rs/pull/484.

docs(compiler): changelog for implicit extensions in HIR

---

crates/apollo-compiler/src/diagnostics.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/enum_.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/interface.rs
crates/apollo-compiler/src/validation/object.rs
crates/apollo-compiler/src/validation/scalar.rs
crates/apollo-compiler/src/validation/schema.rs
crates/apollo-compiler/src/validation/union_.rs
crates/apollo-compiler/test_data/diagnostics/0079_directive_is_unique.graphql
crates/apollo-compiler/test_data/diagnostics/0079_directive_is_unique.txt
crates/apollo-compiler/test_data/diagnostics/0080_directive_is_unique_with_extensions.graphql
crates/apollo-compiler/test_data/diagnostics/0080_directive_is_unique_with_extensions.txt
crates/apollo-compiler/test_data/diagnostics/0081_directive_is_unique_type_system.graphql
crates/apollo-compiler/test_data/diagnostics/0081_directive_is_unique_type_system.txt
crates/apollo-compiler/test_data/ok/0019_extensions.graphql
crates/apollo-compiler/test_data/ok/0019_extensions.txt
crates/apollo-compiler/test_data/ok/0025_unique_directives.graphql
crates/apollo-compiler/test_data/ok/0025_unique_directives.txt

feat(compiler): validate that non-repeatable directives are only used once per location

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md

apollo-compiler@0.7.0

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md

spotted a bug with #501 primarily, which needed a patch, but let's just merge everything else that's new anyways

apollo-compiler@0.7.1

---

crates/apollo-compiler/test_data/diagnostics/0096_schema_extensions.graphql
crates/apollo-compiler/test_data/diagnostics/0096_schema_extensions.txt

This already errors correctly, just need a test.

feat(compiler): add test for non-repeatable directives on schema extensions, closes #474

---

crates/apollo-compiler/src/validation/union_.rs
crates/apollo-compiler/test_data/diagnostics/0100_union_extensions.graphql
crates/apollo-compiler/test_data/diagnostics/0100_union_extensions.txt

feat(compiler): validate union extensions, fixes #478

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md

thought we'd be going to 0.6.0 but looking at the changes i don't think that's necessary 🤔

apollo-parser@0.5.2

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md

[chglg](https://github.com/apollographql/apollo-rs/blob/apollo-compiler%400.9.2/crates/apollo-compiler/CHANGELOG.md#092---2023-05-23)

apollo-compiler@0.9.2

---

crates/apollo-compiler/src/validation/variable.rs
crates/apollo-compiler/test_data/ok/0033_valid_variable_usage.graphql
crates/apollo-compiler/test_data/ok/0033_valid_variable_usage.txt

fix(compiler): nonnullable list variables in nullable args

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md

[changelog](https://github.com/apollographql/apollo-rs/blob/apollo-compiler%400.9.3/crates/apollo-compiler/CHANGELOG.md#093---2023-05-26)

apollo-compiler@0.9.3

---

crates/apollo-compiler/src/database/hir.rs
crates/apollo-compiler/src/validation/value.rs
crates/apollo-compiler/test_data/ok/0032_valid_of_correct_type.graphql
crates/apollo-compiler/test_data/ok/0032_valid_of_correct_type.txt

A possible solution for #562. Would be really curious to hear what other people think!

feat(compiler): accept any scalar type for custom value validation

---

crates/apollo-compiler/src/validation/validation_db.rs

Debugging a router issue and wanted to make sure this isn't the problem (it's not). But we didn't have a test for validating a query against a type system that comes from another compiler instance, so this closes that testing gap.

chore(compiler): add a validation test using shared type system hir

---

crates/apollo-compiler/src/validation/value.rs
crates/apollo-compiler/test_data/ok/0032_valid_of_correct_type.graphql
crates/apollo-compiler/test_data/ok/0032_valid_of_correct_type.txt

per https://github.com/graphql/graphql-spec/issues/688#issuecomment-584010837, custom scalars can take any value, including input objects.

fix(compiler): accept any input object / list AST as custom scalar value

---

crates/apollo-encoder/CHANGELOG.md
crates/apollo-encoder/Cargo.toml
crates/apollo-parser/Cargo.toml
crates/apollo-smith/Cargo.toml

[chg](https://github.com/apollographql/apollo-rs/blob/apollo-encoder%400.6.0/crates/apollo-encoder/CHANGELOG.md)

apollo-encoder@0.6.0

---

crates/apollo-compiler/src/database/hir.rs

apollo-compiler: fix is_introspection for repeated fragment spreads

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-encoder/Cargo.toml

[rendered](https://github.com/apollographql/apollo-rs/blob/apollo-compiler%400.11.0/crates/apollo-compiler/CHANGELOG.md)

apollo-compiler@0.11.0

---

.github/CODEOWNERS

chore(gh): add Simon as a codeowner

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml

[chglg](https://github.com/apollographql/apollo-rs/blob/apollo-parser@0.6.1/crates/apollo-parser/CHANGELOG.md)

apollo-parser@0.6.1

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md

https://github.com/apollographql/apollo-rs/blob/apollo-parser%400.6.2/crates/apollo-parser/CHANGELOG.md#062---2023-09-08

apollo-parser@0.6.2

---

crates/apollo-encoder/CHANGELOG.md
crates/apollo-encoder/Cargo.toml
crates/apollo-encoder/README.md
crates/apollo-parser/Cargo.toml
crates/apollo-smith/Cargo.toml

apollo-encoder@0.8.0

---

crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md

Let’s get https://github.com/apollographql/apollo-rs/pull/704 on crates.io

apollo-parser@0.7.2

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/ast/serialize.rs
crates/apollo-compiler/test_data/ok/0039_string_literals.graphql
crates/apollo-compiler/test_data/ok/0039_string_literals.txt
crates/apollo-compiler/test_data/serializer/ok/0039_string_literals.graphql

Fixes https://github.com/apollographql/apollo-rs/issues/664

Serialize multi-line strings as block strings 

---

crates/apollo-compiler/src/schema/mod.rs

`Schema::type_field` incorrectly returned the definition of __typename for other kinds of types.
This turned out not to be observable from parser input since some other error like "field selection of scalar type `String` must not have subselections" triggers before `type_field` would be called. But might as well make `type_field` more correct now that the patch is written.

__typename only exists on objects, intrefaces, and unions

---

crates/apollo-compiler/src/execution/engine.rs
crates/apollo-compiler/src/execution/introspection_execute.rs
crates/apollo-compiler/src/execution/result_coercion.rs

Made redundant by https://github.com/apollographql/apollo-rs/pull/727

Remove object_type_name parameters when object_type is also given

---

crates/apollo-compiler/src/ast/impls.rs
crates/apollo-compiler/src/schema/mod.rs

Fixes https://github.com/apollographql/apollo-rs/issues/821

Add owned `impl IntoIterator for DirectiveList`

---

crates/apollo-compiler/README.md

```rust
warning: needless `fn main` in doctest
--> crates/apollo-compiler/src/../README.md:95:1
|
95  | / use apollo_compiler::{Schema, ExecutableDocument, Node, executable};
96  | |
97  | | fn main() {
98  | |     let schema_input = r#"
...   |
141 | |     assert_eq!(field_ty, ["ID", "String", "URL"]);
142 | | }
| |_^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_doctest_main
= note: `#[warn(clippy::needless_doctest_main)]` on by default
warning: needless `fn main` in doctest
--> crates/apollo-compiler/src/../README.md:147:1
|
147 | / use apollo_compiler::{Schema, ExecutableDocument, Node, executable};
148 | |
149 | | fn main() {
150 | |     let schema_input = r#"
...   |
206 | |     assert_eq!(in_stock_directive, …
```

Fix new lints in Clippy 1.79

---

crates/apollo-compiler/Cargo.toml
crates/apollo-parser/CHANGELOG.md
crates/apollo-parser/Cargo.toml
crates/apollo-parser/README.md
crates/apollo-smith/Cargo.toml

In order to do a compiler release for Fed

apollo-parser@0.8.0

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/Cargo.toml
crates/apollo-compiler/README.md
crates/apollo-smith/Cargo.toml

Depends https://github.com/apollographql/apollo-rs/pull/890

apollo-compiler@1.0.0-beta.20

---

crates/apollo-compiler/CHANGELOG.md
crates/apollo-compiler/src/schema/validation.rs
crates/apollo-compiler/src/validation/diagnostics.rs
crates/apollo-compiler/src/validation/directive.rs
crates/apollo-compiler/src/validation/enum_.rs
crates/apollo-compiler/src/validation/field.rs
crates/apollo-compiler/src/validation/input_object.rs
crates/apollo-compiler/src/validation/mod.rs
crates/apollo-compiler/test_data/diagnostics/0051_subscription_operation_with_root_introspection_field.txt
crates/apollo-compiler/test_data/diagnostics/0119_reserved_names.graphql
crates/apollo-compiler/test_data/diagnostics/0119_reserved_names.txt
crates/apollo-compiler/test_data/serializer/diagnostics/0119_reserved_named.graphql
crates/apollo-compiler/test_data/serializer/diagnostics/0119_reserved_names.graphql

Fixes https://github.com/apollographql/apollo-rs/issues/743

Validate against reserved names starting with `__` in schemas

---

crates/apollo-compiler/src/executable/mod.rs

This functionality already existed on `Operation` but can make sense more widely, especially on a `FieldSet`.

Add root_fields() and all_fields() to SelectionSet

---

crates/apollo-compiler/src/execution/engine.rs
crates/apollo-compiler/src/execution/input_coercion.rs
crates/apollo-compiler/src/execution/resolver.rs
crates/apollo-compiler/src/execution/result_coercion.rs
crates/apollo-compiler/src/introspection/mod.rs
crates/apollo-compiler/src/introspection/resolvers.rs

This PR does not make any change to public API. New APIs will be in a follow-up PR. Each commit is self-contained and can be reviewed separately.

compiler: Refactor execution code to prepare for giving it a public API
